/*
 * data.js — 出題データ
 * ------------------------------------------------------------------
 * レコード構造 (作り込み問題型):
 *   id          : 一意ID
 *   category    : 5分類 (基礎・構文 / 関数・関数型 / OOP / データ操作 / プログラム構成・堅牢性)
 *   module      : 元になった課題 (M00..M10)
 *   format      : "output"(出力予測) / "fill"(穴埋め・用語) / "debug"(デバッグ)
 *   question    : 問題文
 *   code        : コード片 (任意。null可)
 *   answer      : 正解の選択肢テキスト
 *   distractors : ダミー選択肢3つ (正解と混ぜて毎回シャッフル)
 *   explanation : 解説
 *
 * ここに1要素足すだけで出題が増える。
 * 集合(set)の出力は表示順が不定なので、== 比較で True を問う形にしている。
 */

window.QUIZ_DATA = [
  /* =====================================================================
     基礎・構文 (Module 00)
     ===================================================================== */
  /* ---- 出力予測 ---- */
  { id: "base-out-01", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "print(5 + 3 * 2)",
    answer: "11", distractors: ["16", "13", "10"],
    explanation: "* は + より優先。3*2=6 を先に計算し 5+6=11。" },
  { id: "base-out-02", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "print(7 // 2)",
    answer: "3", distractors: ["3.5", "4", "1"],
    explanation: "// は切り捨て除算。7÷2=3.5 の小数を捨てて 3。" },
  { id: "base-out-03", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "print(7 % 3)",
    answer: "1", distractors: ["2", "0", "2.33"],
    explanation: "% は剰余(あまり)。7 を 3 で割ると商2・あまり1。" },
  { id: "base-out-04", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "print(2 ** 3)",
    answer: "8", distractors: ["6", "9", "23"],
    explanation: "** はべき乗。2 の 3 乗 = 8。" },
  { id: "base-out-05", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: 'print("Py" + "thon")',
    answer: "Python", distractors: ["Py thon", "PyThon", "エラー"],
    explanation: "文字列同士の + は連結。空白は入らない。" },
  { id: "base-out-06", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: 'name = "Rose"\nprint(f"Hi, {name}!")',
    answer: "Hi, Rose!", distractors: ["Hi, {name}!", "Hi, name!", "Hi, Rose"],
    explanation: "f文字列では {name} が値に置き換わる。! はそのまま。" },
  { id: "base-out-07", category: "基礎・構文", module: "M00", format: "output",
    question: "出力される数字を順に並べると?", code: "for i in range(3):\n    print(i)",
    answer: "0 1 2", distractors: ["1 2 3", "0 1 2 3", "1 2"],
    explanation: "range(3) は 0,1,2 を生成する(0始まり・3は含まない)。" },
  { id: "base-out-08", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "print(10 > 3 and 2 > 5)",
    answer: "False", distractors: ["True", "None", "エラー"],
    explanation: "10>3 は True、2>5 は False。and は両方Trueの時だけTrue。" },
  { id: "base-out-09", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: 'print(bool(0), bool(""))',
    answer: "False False", distractors: ["True True", "False True", "0 "],
    explanation: "0 と空文字列はどちらも偽。bool() は False を返す。" },
  { id: "base-out-10", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "x = 5\nx += 3\nprint(x)",
    answer: "8", distractors: ["5", "53", "3"],
    explanation: "x += 3 は x = x + 3 と同じ。5+3=8。" },
  { id: "base-out-11", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: 'print(int("12") + 3)',
    answer: "15", distractors: ['"123"', "123", "エラー"],
    explanation: 'int("12") は整数 12 に変換。12+3=15。' },
  { id: "base-out-12", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: 'print(len("hello"))',
    answer: "5", distractors: ["4", "6", "hello"],
    explanation: "len() は文字数を返す。'hello' は5文字。" },
  /* ---- 穴埋め・用語 ---- */
  { id: "base-fill-01", category: "基礎・構文", module: "M00", format: "fill",
    question: "関数を定義するキーワードは? (___ を埋める)", code: "___ greet():\n    print('hi')",
    answer: "def", distractors: ["func", "define", "fun"],
    explanation: "Python では def で関数を定義する。" },
  { id: "base-fill-02", category: "基礎・構文", module: "M00", format: "fill",
    question: "文字列を整数に変換する組み込み関数は?", code: null,
    answer: "int()", distractors: ["str()", "float()", "num()"],
    explanation: "int() は文字列や小数を整数に変換する。" },
  { id: "base-fill-03", category: "基礎・構文", module: "M00", format: "fill",
    question: "「age が 60 より大きい」を表す条件式は? (___ を埋める)", code: "if age ___ 60:\n    print('収穫OK')",
    answer: ">", distractors: [">=", "<", "=="],
    explanation: "「より大きい(60は含まない)」は >。60以上なら >=。" },
  { id: "base-fill-04", category: "基礎・構文", module: "M00", format: "fill",
    question: "ユーザーからの入力を受け取る組み込み関数は?", code: null,
    answer: "input()", distractors: ["read()", "get()", "scan()"],
    explanation: "input() は1行の入力を文字列として受け取る。" },
  /* ---- デバッグ ---- */
  { id: "base-dbg-01", category: "基礎・構文", module: "M00", format: "debug",
    question: "このコードはエラーになる。正しい1行目は?", code: "if x > 0\n    print(x)",
    answer: "if x > 0:", distractors: ["if x > 0;", "if (x > 0)", "if x > 0 then:"],
    explanation: "if 文の条件の後ろには : が必要。" },
  { id: "base-dbg-02", category: "基礎・構文", module: "M00", format: "debug",
    question: "このコードの誤りは?", code: "def f():\nprint(1)",
    answer: "print(1) をインデントする必要がある", distractors: ["def に () は不要", "コロンが多すぎる", "f は呼び出せない"],
    explanation: "関数の中身はインデント(字下げ)が必要。" },
  { id: "base-dbg-03", category: "基礎・構文", module: "M00", format: "debug",
    question: "値の比較をしたいが誤っている。正しい条件は?", code: "if x = 5:\n    print('five')",
    answer: "x == 5", distractors: ["x = 5", "x := 5", "x === 5"],
    explanation: "= は代入。等しいか比較するときは == を使う。" },

  /* =====================================================================
     関数・関数型 (Module 10)
     ===================================================================== */
  /* ---- 出力予測 ---- */
  { id: "fn-out-01", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "f = lambda x: x * 2\nprint(f(5))",
    answer: "10", distractors: ["5", "25", "エラー"],
    explanation: "lambda x: x*2 は無名関数。f(5) で 5*2=10。" },
  { id: "fn-out-02", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "print(list(map(lambda x: x + 1, [1, 2, 3])))",
    answer: "[2, 3, 4]", distractors: ["[1, 2, 3]", "[2, 4, 6]", "6"],
    explanation: "map は各要素に関数を適用。+1 して [2, 3, 4]。" },
  { id: "fn-out-03", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "print(list(filter(lambda x: x % 2 == 0, [1, 2, 3, 4])))",
    answer: "[2, 4]", distractors: ["[1, 3]", "[1, 2, 3, 4]", "[2, 4, 6]"],
    explanation: "filter は条件が True の要素だけ残す。偶数は 2,4。" },
  { id: "fn-out-04", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "def total(*args):\n    return sum(args)\nprint(total(1, 2, 3))",
    answer: "6", distractors: ["3", "(1, 2, 3)", "エラー"],
    explanation: "*args は複数の引数をタプルで受け取る。sum で 6。" },
  { id: "fn-out-05", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "def f(**kwargs):\n    return kwargs\nprint(f(a=1))",
    answer: "{'a': 1}", distractors: ["(a=1)", "[1]", "a 1"],
    explanation: "**kwargs はキーワード引数を辞書で受け取る。" },
  { id: "fn-out-06", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "def f(x, y=10):\n    return x + y\nprint(f(5))",
    answer: "15", distractors: ["5", "10", "エラー"],
    explanation: "y は省略時 10(デフォルト引数)。5+10=15。" },
  { id: "fn-out-07", category: "関数・関数型", module: "M10", format: "output",
    question: "クロージャの出力は?", code: "def outer():\n    x = 10\n    def inner():\n        return x\n    return inner()\nprint(outer())",
    answer: "10", distractors: ["0", "None", "エラー"],
    explanation: "inner は外側の x を参照できる(クロージャ)。" },
  { id: "fn-out-08", category: "関数・関数型", module: "M10", format: "output",
    question: "デコレータを使った出力は?", code: "def deco(f):\n    def w():\n        return f() + 1\n    return w\n@deco\ndef g():\n    return 5\nprint(g())",
    answer: "6", distractors: ["5", "1", "エラー"],
    explanation: "@deco で g は w に置き換わり、結果に +1 されて 6。" },
  /* ---- 穴埋め・用語 ---- */
  { id: "fn-fill-01", category: "関数・関数型", module: "M10", format: "fill",
    question: "名前のない関数(無名関数)を作るキーワードは?", code: null,
    answer: "lambda", distractors: ["def", "func", "anon"],
    explanation: "lambda 引数: 式 で無名関数を作る。" },
  { id: "fn-fill-02", category: "関数・関数型", module: "M10", format: "fill",
    question: "イテラブルの各要素に関数を適用する組み込み関数は?", code: null,
    answer: "map()", distractors: ["filter()", "apply()", "each()"],
    explanation: "map(関数, イテラブル) は各要素に関数を適用する。" },
  { id: "fn-fill-03", category: "関数・関数型", module: "M10", format: "fill",
    question: "関数の上に @名前 と書いて機能を付け足す仕組みは?", code: "@___\ndef g():\n    ...",
    answer: "デコレータ", distractors: ["ジェネレータ", "クロージャ", "ラムダ"],
    explanation: "デコレータは関数を引数に取り、拡張した関数を返す仕組み。" },
  { id: "fn-fill-04", category: "関数・関数型", module: "M10", format: "fill",
    question: "関数の外側(モジュール全体)の変数に代入することを宣言するキーワードは?", code: null,
    answer: "global", distractors: ["static", "extern", "public"],
    explanation: "global x で関数内からモジュール変数 x に代入できる。" },
  /* ---- デバッグ ---- */
  { id: "fn-dbg-01", category: "関数・関数型", module: "M10", format: "debug",
    question: "このデコレータは動かない。何が足りない?", code: "def deco(f):\n    def w():\n        return f()\n    # ここで?",
    answer: "return w で内側の関数を返す", distractors: ["return f を書く", "w() を呼ぶ", "@deco を付ける"],
    explanation: "デコレータは「ラッパー関数 w 自体」を返す必要がある。" },
  { id: "fn-dbg-02", category: "関数・関数型", module: "M10", format: "debug",
    question: "2引数の無名関数を作りたい。正しいのは?", code: "add = ___\nprint(add(2, 3))  # 5 にしたい",
    answer: "lambda a, b: a + b", distractors: ["lambda a + b", "lambda: a, b", "def a, b: a + b"],
    explanation: "lambda 引数1, 引数2: 式。複数引数はカンマで並べる。" },
  { id: "fn-dbg-03", category: "関数・関数型", module: "M10", format: "debug",
    question: "map の結果をリストで見たい。正しいのは?", code: "r = map(str, [1, 2])\nprint(___)",
    answer: "list(r)", distractors: ["r", "r.list()", "array(r)"],
    explanation: "map はイテレータを返す。list() で中身を取り出す。" },

  /* =====================================================================
     OOP (Module 01 / 05 / 07)
     ===================================================================== */
  /* ---- 出力予測 ---- */
  { id: "oop-out-01", category: "OOP", module: "M01", format: "output",
    question: "次のコードの出力は?", code: "class Plant:\n    def __init__(self):\n        self.name = 'Rose'\nprint(Plant().name)",
    answer: "Rose", distractors: ["None", "Plant", "エラー"],
    explanation: "__init__ で属性 name を設定。生成時に呼ばれる。" },
  { id: "oop-out-02", category: "OOP", module: "M01", format: "output",
    question: "次のコードの出力は?", code: "class Plant:\n    def __init__(self, name):\n        self.name = name\np = Plant('Oak')\nprint(p.name)",
    answer: "Oak", distractors: ["name", "Plant", "エラー"],
    explanation: "引数 name が self.name に格納され、p.name で取り出せる。" },
  { id: "oop-out-03", category: "OOP", module: "M05", format: "output",
    question: "オーバーライドの出力は?", code: "class A:\n    def hi(self):\n        return 'A'\nclass B(A):\n    def hi(self):\n        return 'B'\nprint(B().hi())",
    answer: "B", distractors: ["A", "AB", "エラー"],
    explanation: "B が hi を上書き(オーバーライド)しているので 'B'。" },
  { id: "oop-out-04", category: "OOP", module: "M05", format: "output",
    question: "継承の出力は?", code: "class A:\n    def hi(self):\n        return 'A'\nclass B(A):\n    pass\nprint(B().hi())",
    answer: "A", distractors: ["B", "None", "エラー"],
    explanation: "B は hi を持たないので親 A の hi を継承して使う。" },
  { id: "oop-out-05", category: "OOP", module: "M01", format: "output",
    question: "クラス変数の出力は?", code: "class C:\n    kind = 'tree'\nprint(C.kind)",
    answer: "tree", distractors: ["kind", "C", "エラー"],
    explanation: "kind はクラス変数。C.kind で参照できる。" },
  { id: "oop-out-06", category: "OOP", module: "M02", format: "output",
    question: "次のコードの出力は?", code: "class P:\n    def __init__(self, h):\n        self.h = h\n    def grow(self):\n        self.h += 1\np = P(5)\np.grow()\nprint(p.h)",
    answer: "6", distractors: ["5", "1", "None"],
    explanation: "grow が self.h を 1 増やす。5→6。" },
  { id: "oop-out-07", category: "OOP", module: "M05", format: "output",
    question: "super() を使った出力は?", code: "class A:\n    def __init__(self):\n        self.x = 1\nclass B(A):\n    def __init__(self):\n        super().__init__()\n        self.y = 2\nb = B()\nprint(b.x + b.y)",
    answer: "3", distractors: ["2", "1", "エラー"],
    explanation: "super().__init__() で親の初期化を呼び x=1。y=2 で合計3。" },
  /* ---- 穴埋め・用語 ---- */
  { id: "oop-fill-01", category: "OOP", module: "M01", format: "fill",
    question: "インスタンス生成時に自動で呼ばれる初期化メソッドは?", code: "class P:\n    def ___(self):\n        ...",
    answer: "__init__", distractors: ["__main__", "__new__", "init"],
    explanation: "__init__ はコンストラクタ。生成時に自動で呼ばれる。" },
  { id: "oop-fill-02", category: "OOP", module: "M01", format: "fill",
    question: "メソッドの第一引数、インスタンス自身を指すのは?", code: null,
    answer: "self", distractors: ["this", "me", "cls"],
    explanation: "慣習で self。インスタンス自身を受け取る。" },
  { id: "oop-fill-03", category: "OOP", module: "M01", format: "fill",
    question: "クラスを定義するキーワードは?", code: "___ Plant:\n    ...",
    answer: "class", distractors: ["def", "struct", "object"],
    explanation: "class でクラスを定義する。" },
  { id: "oop-fill-04", category: "OOP", module: "M05", format: "fill",
    question: "親クラスのメソッドを呼び出す組み込みは?", code: "___().__init__()",
    answer: "super", distractors: ["parent", "base", "self"],
    explanation: "super() で親クラスのメソッドを呼べる。" },
  { id: "oop-fill-05", category: "OOP", module: "M07", format: "fill",
    question: "抽象メソッド(サブクラスでの実装を必須にする)を示すデコレータは?", code: null,
    answer: "@abstractmethod", distractors: ["@override", "@abstract", "@virtual"],
    explanation: "abc モジュールの @abstractmethod で抽象メソッドを定義する。" },
  /* ---- デバッグ ---- */
  { id: "oop-dbg-01", category: "OOP", module: "M01", format: "debug",
    question: "メソッド定義が誤っている。正しいのは?", code: "class P:\n    def show():\n        print('hi')",
    answer: "def show(self):", distractors: ["def show:", "def self.show():", "function show():"],
    explanation: "インスタンスメソッドは第一引数 self が必要。" },
  { id: "oop-dbg-02", category: "OOP", module: "M01", format: "debug",
    question: "属性アクセスが誤っている。正しいのは?", code: "class P:\n    def __init__(self):\n        self.n = 1\n    def show(self):\n        print(___)",
    answer: "self.n", distractors: ["n", "P.n", "this.n"],
    explanation: "インスタンス属性は self.n でアクセスする。" },
  { id: "oop-dbg-03", category: "OOP", module: "M01", format: "debug",
    question: "メソッドを呼びたいのに値がおかしい。正しい呼び出しは?", code: "p = Plant()\nresult = p.show___",
    answer: "p.show()", distractors: ["p.show", "p.show[]", "show(p)"],
    explanation: "メソッド呼び出しには () が必要。() が無いと関数オブジェクトのまま。" },

  /* =====================================================================
     データ操作 (Module 03 / 04 / 09)
     ===================================================================== */
  /* ---- 出力予測 ---- */
  { id: "data-out-01", category: "データ操作", module: "M03", format: "output",
    question: "スライスの出力は?", code: "print([1, 2, 3, 4][1:3])",
    answer: "[2, 3]", distractors: ["[1, 2]", "[2, 3, 4]", "[1, 2, 3]"],
    explanation: "[1:3] は添字1から3の手前まで。要素は 2,3。" },
  { id: "data-out-02", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "d = {'a': 1}\nprint(d.get('b', 0))",
    answer: "0", distractors: ["None", "エラー(KeyError)", "1"],
    explanation: "get はキーが無ければ既定値を返す。KeyError にならない。" },
  { id: "data-out-03", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "print({1, 2, 2, 3} == {1, 2, 3})",
    answer: "True", distractors: ["False", "{1, 2, 3}", "エラー"],
    explanation: "set は重複を持たない。{1,2,2,3} は {1,2,3} と等しい。" },
  { id: "data-out-04", category: "データ操作", module: "M03", format: "output",
    question: "リスト内包表記の出力は?", code: "print([x * 2 for x in range(3)])",
    answer: "[0, 2, 4]", distractors: ["[0, 1, 2]", "[2, 4, 6]", "[0, 2, 4, 6]"],
    explanation: "range(3)=0,1,2 を2倍。[0, 2, 4]。" },
  { id: "data-out-05", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "print('a,b,c'.split(','))",
    answer: "['a', 'b', 'c']", distractors: ["'a b c'", "['a,b,c']", "('a', 'b', 'c')"],
    explanation: "split(',') はカンマで分割しリストを返す。" },
  { id: "data-out-06", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "print('x' in 'taxi')",
    answer: "True", distractors: ["False", "1", "エラー"],
    explanation: "in は部分文字列の有無を判定。'taxi' に 'x' は含まれる。" },
  { id: "data-out-07", category: "データ操作", module: "M03", format: "output",
    question: "辞書内包表記の出力は?", code: "print({x: x * x for x in range(3)})",
    answer: "{0: 0, 1: 1, 2: 4}", distractors: ["{0, 1, 4}", "[0, 1, 4]", "{1: 1, 2: 4}"],
    explanation: "キー x、値 x*x の辞書。0,1,2 で {0:0, 1:1, 2:4}。" },
  { id: "data-out-08", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "nums = [1, 2, 3]\nnums.append(4)\nprint(nums)",
    answer: "[1, 2, 3, 4]", distractors: ["[1, 2, 3]", "[4, 1, 2, 3]", "4"],
    explanation: "append は末尾に要素を追加する(破壊的)。" },
  { id: "data-out-09", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "print(sorted([3, 1, 2]))",
    answer: "[1, 2, 3]", distractors: ["[3, 2, 1]", "[3, 1, 2]", "6"],
    explanation: "sorted は新しい昇順リストを返す(元は変えない)。" },
  /* ---- 穴埋め・用語 ---- */
  { id: "data-fill-01", category: "データ操作", module: "M03", format: "fill",
    question: "重複を許さず、順序を持たないコレクション型は?", code: null,
    answer: "set", distractors: ["list", "tuple", "dict"],
    explanation: "set(集合)は重複なし・順序なし。{} や set() で作る。" },
  { id: "data-fill-02", category: "データ操作", module: "M03", format: "fill",
    question: "一度作ると変更できない(イミュータブルな)シーケンス型は?", code: null,
    answer: "tuple", distractors: ["list", "set", "dict"],
    explanation: "tuple は変更不可。() で作る。" },
  { id: "data-fill-03", category: "データ操作", module: "M04", format: "fill",
    question: "ファイルを開く組み込み関数は?", code: '___("data.txt") as f:',
    answer: "open", distractors: ["file", "read", "load"],
    explanation: "open() でファイルを開く。with と組み合わせるのが定石。" },
  { id: "data-fill-04", category: "データ操作", module: "M04", format: "fill",
    question: "処理後にファイルを自動で閉じてくれる構文は?", code: "___ open('a.txt') as f:\n    data = f.read()",
    answer: "with", distractors: ["for", "try", "use"],
    explanation: "with ブロックを抜けると自動で close() される。" },
  /* ---- デバッグ ---- */
  { id: "data-dbg-01", category: "データ操作", module: "M03", format: "debug",
    question: "存在しないキーで KeyError になる。安全に既定値を得るには?", code: "d = {'a': 1}\nx = d___",
    answer: "d.get('b', 0)", distractors: ["d['b']", "d.b", "d.find('b')"],
    explanation: "d['b'] は KeyError。get(キー, 既定値) なら安全。" },
  { id: "data-dbg-02", category: "データ操作", module: "M03", format: "debug",
    question: "タプルは変更できずエラーになる。誤っている行は?", code: "t = (1, 2, 3)\nt[0] = 9",
    answer: "t[0] = 9 （tuple は変更不可）", distractors: ["t = (1, 2, 3)", "括弧が丸ではない", "要素が3つある"],
    explanation: "tuple はイミュータブル。要素の代入はできない(TypeError)。" },
  { id: "data-dbg-03", category: "データ操作", module: "M04", format: "debug",
    question: "ファイルを開いた後 close を忘れがち。推奨される書き方は?", code: "# 安全にファイルを扱うには?",
    answer: "with open('a.txt') as f: で開く", distractors: ["open だけで開く", "close は不要", "import file する"],
    explanation: "with を使えば閉じ忘れを防げる(例外時も自動で閉じる)。" },

  /* =====================================================================
     プログラム構成・堅牢性 (Module 02 / 06 / 08)
     ===================================================================== */
  /* ---- 出力予測 ---- */
  { id: "rob-out-01", category: "プログラム構成・堅牢性", module: "M02", format: "output",
    question: "次のコードの出力は?", code: "try:\n    print(1 / 0)\nexcept ZeroDivisionError:\n    print('err')",
    answer: "err", distractors: ["0", "inf", "プログラムが落ちる"],
    explanation: "1/0 は ZeroDivisionError。except が捕まえて 'err'。" },
  { id: "rob-out-02", category: "プログラム構成・堅牢性", module: "M02", format: "output",
    question: "次のコードの出力は?", code: "try:\n    int('abc')\nexcept ValueError:\n    print('bad')",
    answer: "bad", distractors: ["abc", "0", "エラーで停止"],
    explanation: "int('abc') は ValueError。捕まえて 'bad'。" },
  { id: "rob-out-03", category: "プログラム構成・堅牢性", module: "M02", format: "output",
    question: "次のコードの出力は?", code: "try:\n    x = [1][5]\nexcept IndexError:\n    print('oops')",
    answer: "oops", distractors: ["1", "5", "[]"],
    explanation: "範囲外の添字は IndexError。捕まえて 'oops'。" },
  { id: "rob-out-04", category: "プログラム構成・堅牢性", module: "M02", format: "output",
    question: "例外が起きないとき、出力に含まれないのは?", code: "try:\n    print('try')\nexcept Exception:\n    print('except')\nfinally:\n    print('finally')",
    answer: "except", distractors: ["try", "finally", "何も出ない"],
    explanation: "例外が無いので except は実行されない。try と finally は出る。" },
  { id: "rob-out-05", category: "プログラム構成・堅牢性", module: "M02", format: "output",
    question: "次のコードの出力は?", code: "def check(n):\n    if n < 0:\n        raise ValueError('neg')\n    return n\ntry:\n    check(-1)\nexcept ValueError as e:\n    print(e)",
    answer: "neg", distractors: ["-1", "ValueError", "None"],
    explanation: "raise ValueError('neg') の引数が e として表示される。" },
  { id: "rob-out-06", category: "プログラム構成・堅牢性", module: "M06", format: "output",
    question: "ファイルを直接 python3 で実行したとき __name__ は?", code: "print(__name__)",
    answer: "__main__", distractors: ["main", "ファイル名", "None"],
    explanation: "直接実行すると __name__ は '__main__' になる。" },
  { id: "rob-out-07", category: "プログラム構成・堅牢性", module: "M06", format: "output",
    question: "import の出力は?", code: "import math\nprint(math.sqrt(9))",
    answer: "3.0", distractors: ["3", "9", "エラー"],
    explanation: "math.sqrt は平方根を float で返す。9→3.0。" },
  /* ---- 穴埋め・用語 ---- */
  { id: "rob-fill-01", category: "プログラム構成・堅牢性", module: "M02", format: "fill",
    question: "例外を捕捉するために try と組で使うキーワードは?", code: "try:\n    risky()\n___ Exception:\n    handle()",
    answer: "except", distractors: ["catch", "rescue", "finally"],
    explanation: "Python は try / except で例外を捕捉する。" },
  { id: "rob-fill-02", category: "プログラム構成・堅牢性", module: "M02", format: "fill",
    question: "例外の有無に関わらず必ず最後に実行されるブロックは?", code: null,
    answer: "finally", distractors: ["else", "except", "ensure"],
    explanation: "finally は後始末(クリーンアップ)に使う。必ず実行される。" },
  { id: "rob-fill-03", category: "プログラム構成・堅牢性", module: "M02", format: "fill",
    question: "例外を意図的に発生させるキーワードは?", code: "if n < 0:\n    ___ ValueError('neg')",
    answer: "raise", distractors: ["throw", "error", "panic"],
    explanation: "raise で例外を送出する。" },
  { id: "rob-fill-04", category: "プログラム構成・堅牢性", module: "M02", format: "fill",
    question: "0 で割ったときに発生する例外は?", code: null,
    answer: "ZeroDivisionError", distractors: ["ValueError", "TypeError", "MathError"],
    explanation: "0 除算は ZeroDivisionError。" },
  { id: "rob-fill-05", category: "プログラム構成・堅牢性", module: "M06", format: "fill",
    question: "他のモジュールを取り込むキーワードは?", code: "___ math",
    answer: "import", distractors: ["include", "require", "use"],
    explanation: "import でモジュールを取り込む。from ... import ... も。" },
  { id: "rob-fill-06", category: "プログラム構成・堅牢性", module: "M02", format: "fill",
    question: "自作の例外クラスが継承すべき基底クラスは?", code: "class MyError(___):\n    pass",
    answer: "Exception", distractors: ["Error", "BaseError", "object"],
    explanation: "通常は Exception を継承してカスタム例外を作る。" },
  /* ---- デバッグ ---- */
  { id: "rob-dbg-01", category: "プログラム構成・堅牢性", module: "M02", format: "debug",
    question: "順序が誤っていて構文エラーになる。正しい並びは?", code: "except ValueError:\n    ...\ntry:\n    ...",
    answer: "try を先に書き、except を後に書く", distractors: ["except を先に書く", "finally を最初に書く", "try は不要"],
    explanation: "必ず try が先、except / finally は後。" },
  { id: "rob-dbg-02", category: "プログラム構成・堅牢性", module: "M02", format: "debug",
    question: "あらゆる例外を握りつぶしてバグを隠してしまう。より良いのは?", code: "try:\n    risky()\nexcept:\n    pass",
    answer: "except する例外型を具体的に指定する", distractors: ["pass を print に変える", "try を消す", "そのままで良い"],
    explanation: "裸の except は想定外のバグも隠す。型を指定して捕捉する。" },
  { id: "rob-dbg-03", category: "プログラム構成・堅牢性", module: "M06", format: "debug",
    question: "math モジュールの sqrt を使いたい。正しい import は?", code: "___\nprint(sqrt(9))",
    answer: "from math import sqrt", distractors: ["import sqrt", "import math.sqrt only", "from sqrt import math"],
    explanation: "関数名で直接使うなら from math import sqrt。" },

  /* =====================================================================
     難問追加 (difficulty 2 = Lv11-15 / difficulty 3 = Lv16-20)
     ===================================================================== */

  /* ---- 基礎・構文 / 難(2) ---- */
  { id: "base-h2-01", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(10 / 2)",
    answer: "5.0", distractors: ["5", "2", "2.5"],
    explanation: "/ は常に float を返す(真の除算)。整数で欲しいときは //。" },
  { id: "base-h2-02", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: 'print("ab" * 3)',
    answer: "ababab", distractors: ["ab3", "aaabbb", "エラー"],
    explanation: "文字列 * 整数 は繰り返し連結。" },
  { id: "base-h2-03", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(3 == 3.0)",
    answer: "True", distractors: ["False", "3", "エラー"],
    explanation: "int と float でも値が等しければ == は True。" },
  { id: "base-h2-04", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "x = 1\ny = x\nx = 2\nprint(y)",
    answer: "1", distractors: ["2", "None", "エラー"],
    explanation: "y には代入時点の値(1)が入る。後で x を変えても y は不変。" },
  { id: "base-h2-05", category: "基礎・構文", module: "M00", format: "fill", difficulty: 2,
    question: "論理否定(〜でない)を表す演算子は?", code: "if ___ found:\n    print('not found')",
    answer: "not", distractors: ["!", "~", "no"],
    explanation: "Python の論理否定は not(! ではない)。" },
  /* ---- 基礎・構文 / 最難(3) ---- */
  { id: "base-h3-01", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(0.1 + 0.2 == 0.3)",
    answer: "False", distractors: ["True", "0.3", "エラー"],
    explanation: "浮動小数点の丸め誤差で 0.1+0.2 は 0.3 と厳密一致しない。" },
  { id: "base-h3-02", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(2 ** 3 ** 2)",
    answer: "512", distractors: ["64", "18", "64.0"],
    explanation: "** は右結合。3**2=9 を先に計算し 2**9=512。" },
  { id: "base-h3-03", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: 'print(bool("False"))',
    answer: "True", distractors: ["False", "エラー", "0"],
    explanation: "空でない文字列は真。中身が 'False' でも True。" },
  { id: "base-h3-04", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(3 > 2 > 1)",
    answer: "True", distractors: ["False", "エラー", "2"],
    explanation: "連鎖比較。3>2 and 2>1 と同じ意味で True。" },
  { id: "base-h3-05", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(type(5 / 5))",
    answer: "<class 'float'>", distractors: ["<class 'int'>", "1.0", "1"],
    explanation: "/ の結果は割り切れても float。5/5 は 1.0(float)。" },

  /* ---- 関数・関数型 / 難(2) ---- */
  { id: "fn-h2-01", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print((lambda x: x * x)(4))",
    answer: "16", distractors: ["8", "4", "エラー"],
    explanation: "無名関数を定義してすぐ 4 を渡して呼び出している。" },
  { id: "fn-h2-02", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "def f(a, b=2, c=3):\n    return a + c\nprint(f(1))",
    answer: "4", distractors: ["6", "3", "エラー"],
    explanation: "b は使われず、a=1 と既定 c=3 で 1+3=4。" },
  { id: "fn-h2-03", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(list(map(lambda x, y: x + y, [1, 2], [10, 20])))",
    answer: "[11, 22]", distractors: ["[1, 2, 10, 20]", "[11]", "エラー"],
    explanation: "map は複数イテラブルを同時に取り、要素ごとに関数を適用する。" },
  { id: "fn-h2-04", category: "関数・関数型", module: "M10", format: "fill", difficulty: 2,
    question: "関数が return 1, 2 のようにカンマで複数値を返すと、戻り値の型は?", code: null,
    answer: "tuple", distractors: ["list", "set", "2つのintが別々に返る"],
    explanation: "カンマ区切りの複数値は1つのタプルにまとめて返る。" },
  { id: "fn-h2-05", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "nums = [3, 1, 2]\nprint(sorted(nums, key=lambda x: -x))",
    answer: "[3, 2, 1]", distractors: ["[1, 2, 3]", "[3, 1, 2]", "[-3, -2, -1]"],
    explanation: "key=-x で大小を反転 → 降順に並ぶ。元のリストは変わらない。" },
  /* ---- 関数・関数型 / 最難(3) ---- */
  { id: "fn-h3-01", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "fs = [lambda: i for i in range(3)]\nprint(fs[0]())",
    answer: "2", distractors: ["0", "1", "[0, 1, 2]"],
    explanation: "クロージャは変数 i を参照する。呼ぶ時点では i はループ終了後の 2。" },
  { id: "fn-h3-02", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "def f(x, acc=[]):\n    acc.append(x)\n    return acc\nf(1)\nprint(f(2))",
    answer: "[1, 2]", distractors: ["[2]", "[1]", "[2, 1]"],
    explanation: "可変オブジェクトの既定引数は呼び出し間で共有され、蓄積される(有名な罠)。" },
  { id: "fn-h3-03", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "from functools import reduce\nprint(reduce(lambda a, b: a + b, [1, 2, 3, 4]))",
    answer: "10", distractors: ["24", "[1, 2, 3, 4]", "エラー"],
    explanation: "reduce は左から畳み込む。((1+2)+3)+4 = 10。" },
  { id: "fn-h3-04", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "def counter():\n    n = 0\n    def inc():\n        nonlocal n\n        n += 1\n        return n\n    return inc\nf = counter()\nf()\nprint(f())",
    answer: "2", distractors: ["1", "3", "エラー"],
    explanation: "nonlocal で外側の n を更新するクロージャ。2回呼んで 2。" },
  { id: "fn-h3-05", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "g = (x for x in range(3))\nprint(sum(g))",
    answer: "3", distractors: ["6", "0", "[0, 1, 2]"],
    explanation: "ジェネレータ式。0+1+2=3。一度消費すると空になる。" },

  /* ---- OOP / 難(2) ---- */
  { id: "oop-h2-01", category: "OOP", module: "M01", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "class A:\n    def __init__(self):\n        self.x = 1\na = A()\na.y = 2\nprint(a.x + a.y)",
    answer: "3", distractors: ["1", "2", "エラー"],
    explanation: "インスタンスには後から属性 y を足せる。1+2=3。" },
  { id: "oop-h2-02", category: "OOP", module: "M01", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "class C:\n    n = 0\n    def __init__(self):\n        C.n += 1\nC()\nC()\nprint(C.n)",
    answer: "2", distractors: ["0", "1", "3"],
    explanation: "クラス変数 n を生成のたびに増やす。2回生成で 2。" },
  { id: "oop-h2-03", category: "OOP", module: "M01", format: "fill", difficulty: 2,
    question: "print() で表示される文字列を定義する特殊メソッドは?", code: null,
    answer: "__str__", distractors: ["__init__", "__name__", "__call__"],
    explanation: "__str__ が print 時の見た目を決める(無ければ既定の表現)。" },
  { id: "oop-h2-04", category: "OOP", module: "M05", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "class A:\n    x = 1\nclass B(A):\n    pass\nb = B()\nprint(b.x)",
    answer: "1", distractors: ["0", "None", "エラー"],
    explanation: "B は x を持たないが、親 A のクラス変数を継承して参照できる。" },
  { id: "oop-h2-05", category: "OOP", module: "M07", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "class A:\n    @classmethod\n    def make(cls):\n        return cls()\nprint(type(A.make()) is A)",
    answer: "True", distractors: ["False", "A", "エラー"],
    explanation: "@classmethod は cls を受け取る。cls() で A のインスタンスを生成。" },
  /* ---- OOP / 最難(3) ---- */
  { id: "oop-h3-01", category: "OOP", module: "M05", format: "output", difficulty: 3,
    question: "多重継承の出力は?", code: "class A:\n    def who(self): return 'A'\nclass B(A):\n    def who(self): return 'B'\nclass C(A):\n    def who(self): return 'C'\nclass D(B, C): pass\nprint(D().who())",
    answer: "B", distractors: ["C", "A", "エラー"],
    explanation: "MRO は D→B→C→A。最初に見つかる B.who が使われる。" },
  { id: "oop-h3-02", category: "OOP", module: "M07", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class T:\n    @property\n    def v(self):\n        return 42\nprint(T().v)",
    answer: "42", distractors: ["<property object>", "エラー", "None"],
    explanation: "@property はメソッドを属性のように扱う。() を付けずに呼べる。" },
  { id: "oop-h3-03", category: "OOP", module: "M05", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class P:\n    def __init__(self, n):\n        self.n = n\n    def __eq__(self, o):\n        return self.n == o.n\nprint(P(1) == P(1))",
    answer: "True", distractors: ["False", "エラー", "None"],
    explanation: "__eq__ を定義すると == の比較方法を自分で決められる。" },
  { id: "oop-h3-04", category: "OOP", module: "M01", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "a = [1, 2]\nb = [1, 2]\nprint(a == b, a is b)",
    answer: "True False", distractors: ["True True", "False False", "False True"],
    explanation: "== は値の比較(True)、is は同一オブジェクトか(別物なので False)。" },
  { id: "oop-h3-05", category: "OOP", module: "M01", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class A:\n    def __init__(self):\n        self.__x = 5\n    def get(self):\n        return self.__x\nprint(A().get())",
    answer: "5", distractors: ["エラー", "None", "__x"],
    explanation: "__x は名前マングリングされるが、クラス内のメソッドからは参照できる。" },

  /* ---- データ操作 / 難(2) ---- */
  { id: "data-h2-01", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print([0, 1, 2, 3, 4][::2])",
    answer: "[0, 2, 4]", distractors: ["[0, 1, 2]", "[1, 3]", "[0, 2, 4, 6]"],
    explanation: "[::2] は先頭から1つ飛ばし。0,2,4。" },
  { id: "data-h2-02", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: 'print("python"[-2])',
    answer: "o", distractors: ["n", "p", "エラー"],
    explanation: "負のインデックスは末尾から。-1='n', -2='o'。" },
  { id: "data-h2-03", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "d = {'a': 1, 'b': 2}\nprint(list(d))",
    answer: "['a', 'b']", distractors: ["[1, 2]", "[('a', 1), ('b', 2)]", "{'a', 'b'}"],
    explanation: "辞書を list() するとキーの一覧になる。" },
  { id: "data-h2-04", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print([x for x in range(6) if x % 2])",
    answer: "[1, 3, 5]", distractors: ["[0, 2, 4]", "[1, 2, 3]", "[2, 4]"],
    explanation: "x % 2 が真(=1,3,5)の要素だけ残す内包表記。" },
  { id: "data-h2-05", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(({1, 2, 3} - {2}) == {1, 3})",
    answer: "True", distractors: ["False", "{1, 3}", "エラー"],
    explanation: "差集合 {1,2,3}-{2} は {1,3}。集合は表示順が不定なので比較で確認。" },
  /* ---- データ操作 / 最難(3) ---- */
  { id: "data-h3-01", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "a = [[0]] * 3\na[0].append(1)\nprint(a)",
    answer: "[[0, 1], [0, 1], [0, 1]]", distractors: ["[[0, 1], [0], [0]]", "[[0, 1]]", "エラー"],
    explanation: "* 3 は同じ内側リストの参照を3つ作る。1つ変えると全部変わる。" },
  { id: "data-h3-02", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "g = (x for x in [1, 2])\nprint(list(g), list(g))",
    answer: "[1, 2] []", distractors: ["[1, 2] [1, 2]", "[] []", "エラー"],
    explanation: "ジェネレータは一度消費すると空になる。2回目の list() は空。" },
  { id: "data-h3-03", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(sorted(['bb', 'a', 'ccc'], key=len))",
    answer: "['a', 'bb', 'ccc']", distractors: ["['bb', 'a', 'ccc']", "['ccc', 'bb', 'a']", "['a', 'ccc', 'bb']"],
    explanation: "key=len で文字数の昇順に並べ替える。" },
  { id: "data-h3-04", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "d = {}\nd.setdefault('k', []).append(1)\nprint(d)",
    answer: "{'k': [1]}", distractors: ["{}", "{'k': 1}", "エラー"],
    explanation: "setdefault はキーが無ければ既定値を設定して返す。返ったリストに追加。" },
  { id: "data-h3-05", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print([1, 2, 3][::-1])",
    answer: "[3, 2, 1]", distractors: ["[1, 2, 3]", "[3, 2]", "エラー"],
    explanation: "[::-1] は逆順スライス。リストを反転した新リストを返す。" },

  /* ---- プログラム構成・堅牢性 / 難(2) ---- */
  { id: "rob-h2-01", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "try:\n    int('x')\nexcept (TypeError, ValueError):\n    print('caught')",
    answer: "caught", distractors: ["x", "エラーで停止", ""],
    explanation: "複数の例外型は (A, B) とタプルでまとめて捕捉できる。" },
  { id: "rob-h2-02", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "try:\n    x = 1\nexcept Exception:\n    print('e')\nelse:\n    print('ok')",
    answer: "ok", distractors: ["e", "ok と e の両方", "何も出ない"],
    explanation: "例外が起きなかったときだけ else 節が実行される。" },
  { id: "rob-h2-03", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "try:\n    raise ValueError('a')\nexcept ValueError as e:\n    print(str(e))",
    answer: "a", distractors: ["ValueError", "e", "エラー"],
    explanation: "raise の引数が例外オブジェクト e の文字列表現になる。" },
  { id: "rob-h2-04", category: "プログラム構成・堅牢性", module: "M02", format: "fill", difficulty: 2,
    question: "ValueError と TypeError をまとめて捕捉する except 節は?", code: "try:\n    ...\nexcept ___:\n    ...",
    answer: "(ValueError, TypeError)", distractors: ["ValueError, TypeError", "ValueError | TypeError", "ValueError and TypeError"],
    explanation: "複数型は丸括弧のタプルで指定する。" },
  { id: "rob-h2-05", category: "プログラム構成・堅牢性", module: "M06", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "import math as m\nprint(m.floor(3.7))",
    answer: "3", distractors: ["4", "3.0", "エラー"],
    explanation: "import ... as で別名を付けられる。floor は切り捨てで 3。" },
  /* ---- プログラム構成・堅牢性 / 最難(3) ---- */
  { id: "rob-h3-01", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "def f():\n    try:\n        return 1\n    finally:\n        return 2\nprint(f())",
    answer: "2", distractors: ["1", "エラー", "None"],
    explanation: "finally 内の return は try の return を上書きする(要注意の挙動)。" },
  { id: "rob-h3-02", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class MyErr(Exception):\n    pass\ntry:\n    raise MyErr('x')\nexcept Exception as e:\n    print(type(e).__name__)",
    answer: "MyErr", distractors: ["Exception", "x", "エラー"],
    explanation: "自作例外も Exception で捕捉でき、型名は MyErr。" },
  { id: "rob-h3-03", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class AppErr(Exception):\n    pass\nclass DbErr(AppErr):\n    pass\ntry:\n    raise DbErr()\nexcept AppErr:\n    print('caught')",
    answer: "caught", distractors: ["エラーで停止", "DbErr", ""],
    explanation: "サブクラスの例外は親クラスの型でも捕捉できる(例外の階層)。" },
  { id: "rob-h3-04", category: "プログラム構成・堅牢性", module: "M04", format: "output", difficulty: 3,
    question: "出力を順に並べると?", code: "class C:\n    def __enter__(self):\n        print('in'); return self\n    def __exit__(self, *a):\n        print('out')\nwith C():\n    print('body')",
    answer: "in body out", distractors: ["body in out", "in out body", "body out"],
    explanation: "with は __enter__→本体→__exit__ の順。in→body→out。" },
  { id: "rob-h3-05", category: "プログラム構成・堅牢性", module: "M06", format: "output", difficulty: 3,
    question: "このファイルを直接 python3 で実行したときの出力は?", code: 'print(__name__ == "__main__")',
    answer: "True", distractors: ["False", "__main__", "エラー"],
    explanation: "直接実行時 __name__ は '__main__'。import 時は False になる。" }
];
