/*
 * data.js — 出題データ
 * ------------------------------------------------------------------
 * レコード構造 (作り込み問題型):
 *   id          : 一意ID
 *   category    : 5分類 (基礎・構文 / 関数・関数型 / OOP / データ操作 / プログラム構成・堅牢性)
 *   module      : 元になった課題 (M00..M10)
 *   format      : "output"(出力予測) / "fill"(穴埋め・用語) / "debug"(デバッグ)
 *   question    : 問題文
 *   code        : コード片 (任意。null可)
 *   answer      : 正解の選択肢テキスト
 *   distractors : ダミー選択肢3つ (正解と混ぜて毎回シャッフル)
 *   explanation : 解説
 *
 * ここに1要素足すだけで出題が増える。
 * 集合(set)の出力は表示順が不定なので、== 比較で True を問う形にしている。
 */

window.QUIZ_DATA = [
  /* =====================================================================
     基礎・構文 (Module 00)
     ===================================================================== */
  /* ---- 出力予測 ---- */
  { id: "base-out-01", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "print(5 + 3 * 2)",
    answer: "11", distractors: ["16", "13", "10"],
    explanation: "* は + より優先。3*2=6 を先に計算し 5+6=11。" },
  { id: "base-out-02", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "print(7 // 2)",
    answer: "3", distractors: ["3.5", "4", "1"],
    explanation: "// は切り捨て除算。7÷2=3.5 の小数を捨てて 3。" },
  { id: "base-out-03", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "print(7 % 3)",
    answer: "1", distractors: ["2", "0", "2.33"],
    explanation: "% は剰余(あまり)。7 を 3 で割ると商2・あまり1。" },
  { id: "base-out-04", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "print(2 ** 3)",
    answer: "8", distractors: ["6", "9", "23"],
    explanation: "** はべき乗。2 の 3 乗 = 8。" },
  { id: "base-out-05", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: 'print("Py" + "thon")',
    answer: "Python", distractors: ["Py thon", "PyThon", "エラー"],
    explanation: "文字列同士の + は連結。空白は入らない。" },
  { id: "base-out-06", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: 'name = "Rose"\nprint(f"Hi, {name}!")',
    answer: "Hi, Rose!", distractors: ["Hi, {name}!", "Hi, name!", "Hi, Rose"],
    explanation: "f文字列では {name} が値に置き換わる。! はそのまま。" },
  { id: "base-out-07", category: "基礎・構文", module: "M00", format: "output",
    question: "出力される数字を順に並べると?", code: "for i in range(3):\n    print(i)",
    answer: "0 1 2", distractors: ["1 2 3", "0 1 2 3", "1 2"],
    explanation: "range(3) は 0,1,2 を生成する(0始まり・3は含まない)。" },
  { id: "base-out-08", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "print(10 > 3 and 2 > 5)",
    answer: "False", distractors: ["True", "None", "エラー"],
    explanation: "10>3 は True、2>5 は False。and は両方Trueの時だけTrue。" },
  { id: "base-out-09", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: 'print(bool(0), bool(""))',
    answer: "False False", distractors: ["True True", "False True", "0 "],
    explanation: "0 と空文字列はどちらも偽。bool() は False を返す。" },
  { id: "base-out-10", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: "x = 5\nx += 3\nprint(x)",
    answer: "8", distractors: ["5", "53", "3"],
    explanation: "x += 3 は x = x + 3 と同じ。5+3=8。" },
  { id: "base-out-11", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: 'print(int("12") + 3)',
    answer: "15", distractors: ['"123"', "123", "エラー"],
    explanation: 'int("12") は整数 12 に変換。12+3=15。' },
  { id: "base-out-12", category: "基礎・構文", module: "M00", format: "output",
    question: "次のコードの出力は?", code: 'print(len("hello"))',
    answer: "5", distractors: ["4", "6", "hello"],
    explanation: "len() は文字数を返す。'hello' は5文字。" },
  /* ---- 穴埋め・用語 ---- */
  { id: "base-fill-01", category: "基礎・構文", module: "M00", format: "fill",
    question: "関数を定義するキーワードは? (___ を埋める)", code: "___ greet():\n    print('hi')",
    answer: "def", distractors: ["func", "define", "fun"],
    explanation: "Python では def で関数を定義する。" },
  { id: "base-fill-02", category: "基礎・構文", module: "M00", format: "fill",
    question: "文字列を整数に変換する組み込み関数は?", code: null,
    answer: "int()", distractors: ["str()", "float()", "num()"],
    explanation: "int() は文字列や小数を整数に変換する。" },
  { id: "base-fill-03", category: "基礎・構文", module: "M00", format: "fill",
    question: "「age が 60 より大きい」を表す条件式は? (___ を埋める)", code: "if age ___ 60:\n    print('収穫OK')",
    answer: ">", distractors: [">=", "<", "=="],
    explanation: "「より大きい(60は含まない)」は >。60以上なら >=。" },
  { id: "base-fill-04", category: "基礎・構文", module: "M00", format: "fill",
    question: "ユーザーからの入力を受け取る組み込み関数は?", code: null,
    answer: "input()", distractors: ["read()", "get()", "scan()"],
    explanation: "input() は1行の入力を文字列として受け取る。" },
  /* ---- デバッグ ---- */
  { id: "base-dbg-01", category: "基礎・構文", module: "M00", format: "debug",
    question: "このコードはエラーになる。正しい1行目は?", code: "if x > 0\n    print(x)",
    answer: "if x > 0:", distractors: ["if x > 0;", "if (x > 0)", "if x > 0 then:"],
    explanation: "if 文の条件の後ろには : が必要。" },
  { id: "base-dbg-02", category: "基礎・構文", module: "M00", format: "debug",
    question: "このコードの誤りは?", code: "def f():\nprint(1)",
    answer: "print(1) をインデントする必要がある", distractors: ["def に () は不要", "コロンが多すぎる", "f は呼び出せない"],
    explanation: "関数の中身はインデント(字下げ)が必要。" },
  { id: "base-dbg-03", category: "基礎・構文", module: "M00", format: "debug",
    question: "値の比較をしたいが誤っている。正しい条件は?", code: "if x = 5:\n    print('five')",
    answer: "x == 5", distractors: ["x = 5", "x := 5", "x === 5"],
    explanation: "= は代入。等しいか比較するときは == を使う。" },

  /* =====================================================================
     関数・関数型 (Module 10)
     ===================================================================== */
  /* ---- 出力予測 ---- */
  { id: "fn-out-01", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "f = lambda x: x * 2\nprint(f(5))",
    answer: "10", distractors: ["5", "25", "エラー"],
    explanation: "lambda x: x*2 は無名関数。f(5) で 5*2=10。" },
  { id: "fn-out-02", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "print(list(map(lambda x: x + 1, [1, 2, 3])))",
    answer: "[2, 3, 4]", distractors: ["[1, 2, 3]", "[2, 4, 6]", "6"],
    explanation: "map は各要素に関数を適用。+1 して [2, 3, 4]。" },
  { id: "fn-out-03", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "print(list(filter(lambda x: x % 2 == 0, [1, 2, 3, 4])))",
    answer: "[2, 4]", distractors: ["[1, 3]", "[1, 2, 3, 4]", "[2, 4, 6]"],
    explanation: "filter は条件が True の要素だけ残す。偶数は 2,4。" },
  { id: "fn-out-04", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "def total(*args):\n    return sum(args)\nprint(total(1, 2, 3))",
    answer: "6", distractors: ["3", "(1, 2, 3)", "エラー"],
    explanation: "*args は複数の引数をタプルで受け取る。sum で 6。" },
  { id: "fn-out-05", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "def f(**kwargs):\n    return kwargs\nprint(f(a=1))",
    answer: "{'a': 1}", distractors: ["(a=1)", "[1]", "a 1"],
    explanation: "**kwargs はキーワード引数を辞書で受け取る。" },
  { id: "fn-out-06", category: "関数・関数型", module: "M10", format: "output",
    question: "次のコードの出力は?", code: "def f(x, y=10):\n    return x + y\nprint(f(5))",
    answer: "15", distractors: ["5", "10", "エラー"],
    explanation: "y は省略時 10(デフォルト引数)。5+10=15。" },
  { id: "fn-out-07", category: "関数・関数型", module: "M10", format: "output",
    question: "クロージャの出力は?", code: "def outer():\n    x = 10\n    def inner():\n        return x\n    return inner()\nprint(outer())",
    answer: "10", distractors: ["0", "None", "エラー"],
    explanation: "inner は外側の x を参照できる(クロージャ)。" },
  { id: "fn-out-08", category: "関数・関数型", module: "M10", format: "output",
    question: "デコレータを使った出力は?", code: "def deco(f):\n    def w():\n        return f() + 1\n    return w\n@deco\ndef g():\n    return 5\nprint(g())",
    answer: "6", distractors: ["5", "1", "エラー"],
    explanation: "@deco で g は w に置き換わり、結果に +1 されて 6。" },
  /* ---- 穴埋め・用語 ---- */
  { id: "fn-fill-01", category: "関数・関数型", module: "M10", format: "fill",
    question: "名前のない関数(無名関数)を作るキーワードは?", code: null,
    answer: "lambda", distractors: ["def", "func", "anon"],
    explanation: "lambda 引数: 式 で無名関数を作る。" },
  { id: "fn-fill-02", category: "関数・関数型", module: "M10", format: "fill",
    question: "イテラブルの各要素に関数を適用する組み込み関数は?", code: null,
    answer: "map()", distractors: ["filter()", "apply()", "each()"],
    explanation: "map(関数, イテラブル) は各要素に関数を適用する。" },
  { id: "fn-fill-03", category: "関数・関数型", module: "M10", format: "fill",
    question: "関数の上に @名前 と書いて機能を付け足す仕組みは?", code: "@___\ndef g():\n    ...",
    answer: "デコレータ", distractors: ["ジェネレータ", "クロージャ", "ラムダ"],
    explanation: "デコレータは関数を引数に取り、拡張した関数を返す仕組み。" },
  { id: "fn-fill-04", category: "関数・関数型", module: "M10", format: "fill",
    question: "関数の外側(モジュール全体)の変数に代入することを宣言するキーワードは?", code: null,
    answer: "global", distractors: ["static", "extern", "public"],
    explanation: "global x で関数内からモジュール変数 x に代入できる。" },
  /* ---- デバッグ ---- */
  { id: "fn-dbg-01", category: "関数・関数型", module: "M10", format: "debug",
    question: "このデコレータは動かない。何が足りない?", code: "def deco(f):\n    def w():\n        return f()\n    # ここで?",
    answer: "return w で内側の関数を返す", distractors: ["return f を書く", "w() を呼ぶ", "@deco を付ける"],
    explanation: "デコレータは「ラッパー関数 w 自体」を返す必要がある。" },
  { id: "fn-dbg-02", category: "関数・関数型", module: "M10", format: "debug",
    question: "2引数の無名関数を作りたい。正しいのは?", code: "add = ___\nprint(add(2, 3))  # 5 にしたい",
    answer: "lambda a, b: a + b", distractors: ["lambda a + b", "lambda: a, b", "def a, b: a + b"],
    explanation: "lambda 引数1, 引数2: 式。複数引数はカンマで並べる。" },
  { id: "fn-dbg-03", category: "関数・関数型", module: "M10", format: "debug",
    question: "map の結果をリストで見たい。正しいのは?", code: "r = map(str, [1, 2])\nprint(___)",
    answer: "list(r)", distractors: ["r", "r.list()", "array(r)"],
    explanation: "map はイテレータを返す。list() で中身を取り出す。" },

  /* =====================================================================
     OOP (Module 01 / 05 / 07)
     ===================================================================== */
  /* ---- 出力予測 ---- */
  { id: "oop-out-01", category: "OOP", module: "M01", format: "output",
    question: "次のコードの出力は?", code: "class Plant:\n    def __init__(self):\n        self.name = 'Rose'\nprint(Plant().name)",
    answer: "Rose", distractors: ["None", "Plant", "エラー"],
    explanation: "__init__ で属性 name を設定。生成時に呼ばれる。" },
  { id: "oop-out-02", category: "OOP", module: "M01", format: "output",
    question: "次のコードの出力は?", code: "class Plant:\n    def __init__(self, name):\n        self.name = name\np = Plant('Oak')\nprint(p.name)",
    answer: "Oak", distractors: ["name", "Plant", "エラー"],
    explanation: "引数 name が self.name に格納され、p.name で取り出せる。" },
  { id: "oop-out-03", category: "OOP", module: "M05", format: "output",
    question: "オーバーライドの出力は?", code: "class A:\n    def hi(self):\n        return 'A'\nclass B(A):\n    def hi(self):\n        return 'B'\nprint(B().hi())",
    answer: "B", distractors: ["A", "AB", "エラー"],
    explanation: "B が hi を上書き(オーバーライド)しているので 'B'。" },
  { id: "oop-out-04", category: "OOP", module: "M05", format: "output",
    question: "継承の出力は?", code: "class A:\n    def hi(self):\n        return 'A'\nclass B(A):\n    pass\nprint(B().hi())",
    answer: "A", distractors: ["B", "None", "エラー"],
    explanation: "B は hi を持たないので親 A の hi を継承して使う。" },
  { id: "oop-out-05", category: "OOP", module: "M01", format: "output",
    question: "クラス変数の出力は?", code: "class C:\n    kind = 'tree'\nprint(C.kind)",
    answer: "tree", distractors: ["kind", "C", "エラー"],
    explanation: "kind はクラス変数。C.kind で参照できる。" },
  { id: "oop-out-06", category: "OOP", module: "M02", format: "output",
    question: "次のコードの出力は?", code: "class P:\n    def __init__(self, h):\n        self.h = h\n    def grow(self):\n        self.h += 1\np = P(5)\np.grow()\nprint(p.h)",
    answer: "6", distractors: ["5", "1", "None"],
    explanation: "grow が self.h を 1 増やす。5→6。" },
  { id: "oop-out-07", category: "OOP", module: "M05", format: "output",
    question: "super() を使った出力は?", code: "class A:\n    def __init__(self):\n        self.x = 1\nclass B(A):\n    def __init__(self):\n        super().__init__()\n        self.y = 2\nb = B()\nprint(b.x + b.y)",
    answer: "3", distractors: ["2", "1", "エラー"],
    explanation: "super().__init__() で親の初期化を呼び x=1。y=2 で合計3。" },
  /* ---- 穴埋め・用語 ---- */
  { id: "oop-fill-01", category: "OOP", module: "M01", format: "fill",
    question: "インスタンス生成時に自動で呼ばれる初期化メソッドは?", code: "class P:\n    def ___(self):\n        ...",
    answer: "__init__", distractors: ["__main__", "__new__", "init"],
    explanation: "__init__ はコンストラクタ。生成時に自動で呼ばれる。" },
  { id: "oop-fill-02", category: "OOP", module: "M01", format: "fill",
    question: "メソッドの第一引数、インスタンス自身を指すのは?", code: null,
    answer: "self", distractors: ["this", "me", "cls"],
    explanation: "慣習で self。インスタンス自身を受け取る。" },
  { id: "oop-fill-03", category: "OOP", module: "M01", format: "fill",
    question: "クラスを定義するキーワードは?", code: "___ Plant:\n    ...",
    answer: "class", distractors: ["def", "struct", "object"],
    explanation: "class でクラスを定義する。" },
  { id: "oop-fill-04", category: "OOP", module: "M05", format: "fill",
    question: "親クラスのメソッドを呼び出す組み込みは?", code: "___().__init__()",
    answer: "super", distractors: ["parent", "base", "self"],
    explanation: "super() で親クラスのメソッドを呼べる。" },
  { id: "oop-fill-05", category: "OOP", module: "M07", format: "fill",
    question: "抽象メソッド(サブクラスでの実装を必須にする)を示すデコレータは?", code: null,
    answer: "@abstractmethod", distractors: ["@override", "@abstract", "@virtual"],
    explanation: "abc モジュールの @abstractmethod で抽象メソッドを定義する。" },
  /* ---- デバッグ ---- */
  { id: "oop-dbg-01", category: "OOP", module: "M01", format: "debug",
    question: "メソッド定義が誤っている。正しいのは?", code: "class P:\n    def show():\n        print('hi')",
    answer: "def show(self):", distractors: ["def show:", "def self.show():", "function show():"],
    explanation: "インスタンスメソッドは第一引数 self が必要。" },
  { id: "oop-dbg-02", category: "OOP", module: "M01", format: "debug",
    question: "属性アクセスが誤っている。正しいのは?", code: "class P:\n    def __init__(self):\n        self.n = 1\n    def show(self):\n        print(___)",
    answer: "self.n", distractors: ["n", "P.n", "this.n"],
    explanation: "インスタンス属性は self.n でアクセスする。" },
  { id: "oop-dbg-03", category: "OOP", module: "M01", format: "debug",
    question: "メソッドを呼びたいのに値がおかしい。正しい呼び出しは?", code: "p = Plant()\nresult = p.show___",
    answer: "p.show()", distractors: ["p.show", "p.show[]", "show(p)"],
    explanation: "メソッド呼び出しには () が必要。() が無いと関数オブジェクトのまま。" },

  /* =====================================================================
     データ操作 (Module 03 / 04 / 09)
     ===================================================================== */
  /* ---- 出力予測 ---- */
  { id: "data-out-01", category: "データ操作", module: "M03", format: "output",
    question: "スライスの出力は?", code: "print([1, 2, 3, 4][1:3])",
    answer: "[2, 3]", distractors: ["[1, 2]", "[2, 3, 4]", "[1, 2, 3]"],
    explanation: "[1:3] は添字1から3の手前まで。要素は 2,3。" },
  { id: "data-out-02", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "d = {'a': 1}\nprint(d.get('b', 0))",
    answer: "0", distractors: ["None", "エラー(KeyError)", "1"],
    explanation: "get はキーが無ければ既定値を返す。KeyError にならない。" },
  { id: "data-out-03", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "print({1, 2, 2, 3} == {1, 2, 3})",
    answer: "True", distractors: ["False", "{1, 2, 3}", "エラー"],
    explanation: "set は重複を持たない。{1,2,2,3} は {1,2,3} と等しい。" },
  { id: "data-out-04", category: "データ操作", module: "M03", format: "output",
    question: "リスト内包表記の出力は?", code: "print([x * 2 for x in range(3)])",
    answer: "[0, 2, 4]", distractors: ["[0, 1, 2]", "[2, 4, 6]", "[0, 2, 4, 6]"],
    explanation: "range(3)=0,1,2 を2倍。[0, 2, 4]。" },
  { id: "data-out-05", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "print('a,b,c'.split(','))",
    answer: "['a', 'b', 'c']", distractors: ["'a b c'", "['a,b,c']", "('a', 'b', 'c')"],
    explanation: "split(',') はカンマで分割しリストを返す。" },
  { id: "data-out-06", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "print('x' in 'taxi')",
    answer: "True", distractors: ["False", "1", "エラー"],
    explanation: "in は部分文字列の有無を判定。'taxi' に 'x' は含まれる。" },
  { id: "data-out-07", category: "データ操作", module: "M03", format: "output",
    question: "辞書内包表記の出力は?", code: "print({x: x * x for x in range(3)})",
    answer: "{0: 0, 1: 1, 2: 4}", distractors: ["{0, 1, 4}", "[0, 1, 4]", "{1: 1, 2: 4}"],
    explanation: "キー x、値 x*x の辞書。0,1,2 で {0:0, 1:1, 2:4}。" },
  { id: "data-out-08", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "nums = [1, 2, 3]\nnums.append(4)\nprint(nums)",
    answer: "[1, 2, 3, 4]", distractors: ["[1, 2, 3]", "[4, 1, 2, 3]", "4"],
    explanation: "append は末尾に要素を追加する(破壊的)。" },
  { id: "data-out-09", category: "データ操作", module: "M03", format: "output",
    question: "次のコードの出力は?", code: "print(sorted([3, 1, 2]))",
    answer: "[1, 2, 3]", distractors: ["[3, 2, 1]", "[3, 1, 2]", "6"],
    explanation: "sorted は新しい昇順リストを返す(元は変えない)。" },
  /* ---- 穴埋め・用語 ---- */
  { id: "data-fill-01", category: "データ操作", module: "M03", format: "fill",
    question: "重複を許さず、順序を持たないコレクション型は?", code: null,
    answer: "set", distractors: ["list", "tuple", "dict"],
    explanation: "set(集合)は重複なし・順序なし。{} や set() で作る。" },
  { id: "data-fill-02", category: "データ操作", module: "M03", format: "fill",
    question: "一度作ると変更できない(イミュータブルな)シーケンス型は?", code: null,
    answer: "tuple", distractors: ["list", "set", "dict"],
    explanation: "tuple は変更不可。() で作る。" },
  { id: "data-fill-03", category: "データ操作", module: "M04", format: "fill",
    question: "ファイルを開く組み込み関数は?", code: '___("data.txt") as f:',
    answer: "open", distractors: ["file", "read", "load"],
    explanation: "open() でファイルを開く。with と組み合わせるのが定石。" },
  { id: "data-fill-04", category: "データ操作", module: "M04", format: "fill",
    question: "処理後にファイルを自動で閉じてくれる構文は?", code: "___ open('a.txt') as f:\n    data = f.read()",
    answer: "with", distractors: ["for", "try", "use"],
    explanation: "with ブロックを抜けると自動で close() される。" },
  /* ---- デバッグ ---- */
  { id: "data-dbg-01", category: "データ操作", module: "M03", format: "debug",
    question: "存在しないキーで KeyError になる。安全に既定値を得るには?", code: "d = {'a': 1}\nx = d___",
    answer: "d.get('b', 0)", distractors: ["d['b']", "d.b", "d.find('b')"],
    explanation: "d['b'] は KeyError。get(キー, 既定値) なら安全。" },
  { id: "data-dbg-02", category: "データ操作", module: "M03", format: "debug",
    question: "タプルは変更できずエラーになる。誤っている行は?", code: "t = (1, 2, 3)\nt[0] = 9",
    answer: "t[0] = 9 （tuple は変更不可）", distractors: ["t = (1, 2, 3)", "括弧が丸ではない", "要素が3つある"],
    explanation: "tuple はイミュータブル。要素の代入はできない(TypeError)。" },
  { id: "data-dbg-03", category: "データ操作", module: "M04", format: "debug",
    question: "ファイルを開いた後 close を忘れがち。推奨される書き方は?", code: "# 安全にファイルを扱うには?",
    answer: "with open('a.txt') as f: で開く", distractors: ["open だけで開く", "close は不要", "import file する"],
    explanation: "with を使えば閉じ忘れを防げる(例外時も自動で閉じる)。" },

  /* =====================================================================
     プログラム構成・堅牢性 (Module 02 / 06 / 08)
     ===================================================================== */
  /* ---- 出力予測 ---- */
  { id: "rob-out-01", category: "プログラム構成・堅牢性", module: "M02", format: "output",
    question: "次のコードの出力は?", code: "try:\n    print(1 / 0)\nexcept ZeroDivisionError:\n    print('err')",
    answer: "err", distractors: ["0", "inf", "プログラムが落ちる"],
    explanation: "1/0 は ZeroDivisionError。except が捕まえて 'err'。" },
  { id: "rob-out-02", category: "プログラム構成・堅牢性", module: "M02", format: "output",
    question: "次のコードの出力は?", code: "try:\n    int('abc')\nexcept ValueError:\n    print('bad')",
    answer: "bad", distractors: ["abc", "0", "エラーで停止"],
    explanation: "int('abc') は ValueError。捕まえて 'bad'。" },
  { id: "rob-out-03", category: "プログラム構成・堅牢性", module: "M02", format: "output",
    question: "次のコードの出力は?", code: "try:\n    x = [1][5]\nexcept IndexError:\n    print('oops')",
    answer: "oops", distractors: ["1", "5", "[]"],
    explanation: "範囲外の添字は IndexError。捕まえて 'oops'。" },
  { id: "rob-out-04", category: "プログラム構成・堅牢性", module: "M02", format: "output",
    question: "例外が起きないとき、出力に含まれないのは?", code: "try:\n    print('try')\nexcept Exception:\n    print('except')\nfinally:\n    print('finally')",
    answer: "except", distractors: ["try", "finally", "何も出ない"],
    explanation: "例外が無いので except は実行されない。try と finally は出る。" },
  { id: "rob-out-05", category: "プログラム構成・堅牢性", module: "M02", format: "output",
    question: "次のコードの出力は?", code: "def check(n):\n    if n < 0:\n        raise ValueError('neg')\n    return n\ntry:\n    check(-1)\nexcept ValueError as e:\n    print(e)",
    answer: "neg", distractors: ["-1", "ValueError", "None"],
    explanation: "raise ValueError('neg') の引数が e として表示される。" },
  { id: "rob-out-06", category: "プログラム構成・堅牢性", module: "M06", format: "output",
    question: "ファイルを直接 python3 で実行したとき __name__ は?", code: "print(__name__)",
    answer: "__main__", distractors: ["main", "ファイル名", "None"],
    explanation: "直接実行すると __name__ は '__main__' になる。" },
  { id: "rob-out-07", category: "プログラム構成・堅牢性", module: "M06", format: "output",
    question: "import の出力は?", code: "import math\nprint(math.sqrt(9))",
    answer: "3.0", distractors: ["3", "9", "エラー"],
    explanation: "math.sqrt は平方根を float で返す。9→3.0。" },
  /* ---- 穴埋め・用語 ---- */
  { id: "rob-fill-01", category: "プログラム構成・堅牢性", module: "M02", format: "fill",
    question: "例外を捕捉するために try と組で使うキーワードは?", code: "try:\n    risky()\n___ Exception:\n    handle()",
    answer: "except", distractors: ["catch", "rescue", "finally"],
    explanation: "Python は try / except で例外を捕捉する。" },
  { id: "rob-fill-02", category: "プログラム構成・堅牢性", module: "M02", format: "fill",
    question: "例外の有無に関わらず必ず最後に実行されるブロックは?", code: null,
    answer: "finally", distractors: ["else", "except", "ensure"],
    explanation: "finally は後始末(クリーンアップ)に使う。必ず実行される。" },
  { id: "rob-fill-03", category: "プログラム構成・堅牢性", module: "M02", format: "fill",
    question: "例外を意図的に発生させるキーワードは?", code: "if n < 0:\n    ___ ValueError('neg')",
    answer: "raise", distractors: ["throw", "error", "panic"],
    explanation: "raise で例外を送出する。" },
  { id: "rob-fill-04", category: "プログラム構成・堅牢性", module: "M02", format: "fill",
    question: "0 で割ったときに発生する例外は?", code: null,
    answer: "ZeroDivisionError", distractors: ["ValueError", "TypeError", "MathError"],
    explanation: "0 除算は ZeroDivisionError。" },
  { id: "rob-fill-05", category: "プログラム構成・堅牢性", module: "M06", format: "fill",
    question: "他のモジュールを取り込むキーワードは?", code: "___ math",
    answer: "import", distractors: ["include", "require", "use"],
    explanation: "import でモジュールを取り込む。from ... import ... も。" },
  { id: "rob-fill-06", category: "プログラム構成・堅牢性", module: "M02", format: "fill",
    question: "自作の例外クラスが継承すべき基底クラスは?", code: "class MyError(___):\n    pass",
    answer: "Exception", distractors: ["Error", "BaseError", "object"],
    explanation: "通常は Exception を継承してカスタム例外を作る。" },
  /* ---- デバッグ ---- */
  { id: "rob-dbg-01", category: "プログラム構成・堅牢性", module: "M02", format: "debug",
    question: "順序が誤っていて構文エラーになる。正しい並びは?", code: "except ValueError:\n    ...\ntry:\n    ...",
    answer: "try を先に書き、except を後に書く", distractors: ["except を先に書く", "finally を最初に書く", "try は不要"],
    explanation: "必ず try が先、except / finally は後。" },
  { id: "rob-dbg-02", category: "プログラム構成・堅牢性", module: "M02", format: "debug",
    question: "あらゆる例外を握りつぶしてバグを隠してしまう。より良いのは?", code: "try:\n    risky()\nexcept:\n    pass",
    answer: "except する例外型を具体的に指定する", distractors: ["pass を print に変える", "try を消す", "そのままで良い"],
    explanation: "裸の except は想定外のバグも隠す。型を指定して捕捉する。" },
  { id: "rob-dbg-03", category: "プログラム構成・堅牢性", module: "M06", format: "debug",
    question: "math モジュールの sqrt を使いたい。正しい import は?", code: "___\nprint(sqrt(9))",
    answer: "from math import sqrt", distractors: ["import sqrt", "import math.sqrt only", "from sqrt import math"],
    explanation: "関数名で直接使うなら from math import sqrt。" },

  /* =====================================================================
     難問追加 (difficulty 2 = Lv11-15 / difficulty 3 = Lv16-20)
     ===================================================================== */

  /* ---- 基礎・構文 / 難(2) ---- */
  { id: "base-h2-01", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(10 / 2)",
    answer: "5.0", distractors: ["5", "2", "2.5"],
    explanation: "/ は常に float を返す(真の除算)。整数で欲しいときは //。" },
  { id: "base-h2-02", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: 'print("ab" * 3)',
    answer: "ababab", distractors: ["ab3", "aaabbb", "エラー"],
    explanation: "文字列 * 整数 は繰り返し連結。" },
  { id: "base-h2-03", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(3 == 3.0)",
    answer: "True", distractors: ["False", "3", "エラー"],
    explanation: "int と float でも値が等しければ == は True。" },
  { id: "base-h2-04", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "x = 1\ny = x\nx = 2\nprint(y)",
    answer: "1", distractors: ["2", "None", "エラー"],
    explanation: "y には代入時点の値(1)が入る。後で x を変えても y は不変。" },
  { id: "base-h2-05", category: "基礎・構文", module: "M00", format: "fill", difficulty: 2,
    question: "論理否定(〜でない)を表す演算子は?", code: "if ___ found:\n    print('not found')",
    answer: "not", distractors: ["!", "~", "no"],
    explanation: "Python の論理否定は not(! ではない)。" },
  /* ---- 基礎・構文 / 最難(3) ---- */
  { id: "base-h3-01", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(0.1 + 0.2 == 0.3)",
    answer: "False", distractors: ["True", "0.3", "エラー"],
    explanation: "浮動小数点の丸め誤差で 0.1+0.2 は 0.3 と厳密一致しない。" },
  { id: "base-h3-02", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(2 ** 3 ** 2)",
    answer: "512", distractors: ["64", "18", "64.0"],
    explanation: "** は右結合。3**2=9 を先に計算し 2**9=512。" },
  { id: "base-h3-03", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: 'print(bool("False"))',
    answer: "True", distractors: ["False", "エラー", "0"],
    explanation: "空でない文字列は真。中身が 'False' でも True。" },
  { id: "base-h3-04", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(3 > 2 > 1)",
    answer: "True", distractors: ["False", "エラー", "2"],
    explanation: "連鎖比較。3>2 and 2>1 と同じ意味で True。" },
  { id: "base-h3-05", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(type(5 / 5))",
    answer: "<class 'float'>", distractors: ["<class 'int'>", "1.0", "1"],
    explanation: "/ の結果は割り切れても float。5/5 は 1.0(float)。" },

  /* ---- 関数・関数型 / 難(2) ---- */
  { id: "fn-h2-01", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print((lambda x: x * x)(4))",
    answer: "16", distractors: ["8", "4", "エラー"],
    explanation: "無名関数を定義してすぐ 4 を渡して呼び出している。" },
  { id: "fn-h2-02", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "def f(a, b=2, c=3):\n    return a + c\nprint(f(1))",
    answer: "4", distractors: ["6", "3", "エラー"],
    explanation: "b は使われず、a=1 と既定 c=3 で 1+3=4。" },
  { id: "fn-h2-03", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(list(map(lambda x, y: x + y, [1, 2], [10, 20])))",
    answer: "[11, 22]", distractors: ["[1, 2, 10, 20]", "[11]", "エラー"],
    explanation: "map は複数イテラブルを同時に取り、要素ごとに関数を適用する。" },
  { id: "fn-h2-04", category: "関数・関数型", module: "M10", format: "fill", difficulty: 2,
    question: "関数が return 1, 2 のようにカンマで複数値を返すと、戻り値の型は?", code: null,
    answer: "tuple", distractors: ["list", "set", "2つのintが別々に返る"],
    explanation: "カンマ区切りの複数値は1つのタプルにまとめて返る。" },
  { id: "fn-h2-05", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "nums = [3, 1, 2]\nprint(sorted(nums, key=lambda x: -x))",
    answer: "[3, 2, 1]", distractors: ["[1, 2, 3]", "[3, 1, 2]", "[-3, -2, -1]"],
    explanation: "key=-x で大小を反転 → 降順に並ぶ。元のリストは変わらない。" },
  /* ---- 関数・関数型 / 最難(3) ---- */
  { id: "fn-h3-01", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "fs = [lambda: i for i in range(3)]\nprint(fs[0]())",
    answer: "2", distractors: ["0", "1", "[0, 1, 2]"],
    explanation: "クロージャは変数 i を参照する。呼ぶ時点では i はループ終了後の 2。" },
  { id: "fn-h3-02", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "def f(x, acc=[]):\n    acc.append(x)\n    return acc\nf(1)\nprint(f(2))",
    answer: "[1, 2]", distractors: ["[2]", "[1]", "[2, 1]"],
    explanation: "可変オブジェクトの既定引数は呼び出し間で共有され、蓄積される(有名な罠)。" },
  { id: "fn-h3-03", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "from functools import reduce\nprint(reduce(lambda a, b: a + b, [1, 2, 3, 4]))",
    answer: "10", distractors: ["24", "[1, 2, 3, 4]", "エラー"],
    explanation: "reduce は左から畳み込む。((1+2)+3)+4 = 10。" },
  { id: "fn-h3-04", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "def counter():\n    n = 0\n    def inc():\n        nonlocal n\n        n += 1\n        return n\n    return inc\nf = counter()\nf()\nprint(f())",
    answer: "2", distractors: ["1", "3", "エラー"],
    explanation: "nonlocal で外側の n を更新するクロージャ。2回呼んで 2。" },
  { id: "fn-h3-05", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "g = (x for x in range(3))\nprint(sum(g))",
    answer: "3", distractors: ["6", "0", "[0, 1, 2]"],
    explanation: "ジェネレータ式。0+1+2=3。一度消費すると空になる。" },

  /* ---- OOP / 難(2) ---- */
  { id: "oop-h2-01", category: "OOP", module: "M01", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "class A:\n    def __init__(self):\n        self.x = 1\na = A()\na.y = 2\nprint(a.x + a.y)",
    answer: "3", distractors: ["1", "2", "エラー"],
    explanation: "インスタンスには後から属性 y を足せる。1+2=3。" },
  { id: "oop-h2-02", category: "OOP", module: "M01", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "class C:\n    n = 0\n    def __init__(self):\n        C.n += 1\nC()\nC()\nprint(C.n)",
    answer: "2", distractors: ["0", "1", "3"],
    explanation: "クラス変数 n を生成のたびに増やす。2回生成で 2。" },
  { id: "oop-h2-03", category: "OOP", module: "M01", format: "fill", difficulty: 2,
    question: "print() で表示される文字列を定義する特殊メソッドは?", code: null,
    answer: "__str__", distractors: ["__init__", "__name__", "__call__"],
    explanation: "__str__ が print 時の見た目を決める(無ければ既定の表現)。" },
  { id: "oop-h2-04", category: "OOP", module: "M05", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "class A:\n    x = 1\nclass B(A):\n    pass\nb = B()\nprint(b.x)",
    answer: "1", distractors: ["0", "None", "エラー"],
    explanation: "B は x を持たないが、親 A のクラス変数を継承して参照できる。" },
  { id: "oop-h2-05", category: "OOP", module: "M07", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "class A:\n    @classmethod\n    def make(cls):\n        return cls()\nprint(type(A.make()) is A)",
    answer: "True", distractors: ["False", "A", "エラー"],
    explanation: "@classmethod は cls を受け取る。cls() で A のインスタンスを生成。" },
  /* ---- OOP / 最難(3) ---- */
  { id: "oop-h3-01", category: "OOP", module: "M05", format: "output", difficulty: 3,
    question: "多重継承の出力は?", code: "class A:\n    def who(self): return 'A'\nclass B(A):\n    def who(self): return 'B'\nclass C(A):\n    def who(self): return 'C'\nclass D(B, C): pass\nprint(D().who())",
    answer: "B", distractors: ["C", "A", "エラー"],
    explanation: "MRO は D→B→C→A。最初に見つかる B.who が使われる。" },
  { id: "oop-h3-02", category: "OOP", module: "M07", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class T:\n    @property\n    def v(self):\n        return 42\nprint(T().v)",
    answer: "42", distractors: ["<property object>", "エラー", "None"],
    explanation: "@property はメソッドを属性のように扱う。() を付けずに呼べる。" },
  { id: "oop-h3-03", category: "OOP", module: "M05", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class P:\n    def __init__(self, n):\n        self.n = n\n    def __eq__(self, o):\n        return self.n == o.n\nprint(P(1) == P(1))",
    answer: "True", distractors: ["False", "エラー", "None"],
    explanation: "__eq__ を定義すると == の比較方法を自分で決められる。" },
  { id: "oop-h3-04", category: "OOP", module: "M01", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "a = [1, 2]\nb = [1, 2]\nprint(a == b, a is b)",
    answer: "True False", distractors: ["True True", "False False", "False True"],
    explanation: "== は値の比較(True)、is は同一オブジェクトか(別物なので False)。" },
  { id: "oop-h3-05", category: "OOP", module: "M01", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class A:\n    def __init__(self):\n        self.__x = 5\n    def get(self):\n        return self.__x\nprint(A().get())",
    answer: "5", distractors: ["エラー", "None", "__x"],
    explanation: "__x は名前マングリングされるが、クラス内のメソッドからは参照できる。" },

  /* ---- データ操作 / 難(2) ---- */
  { id: "data-h2-01", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print([0, 1, 2, 3, 4][::2])",
    answer: "[0, 2, 4]", distractors: ["[0, 1, 2]", "[1, 3]", "[0, 2, 4, 6]"],
    explanation: "[::2] は先頭から1つ飛ばし。0,2,4。" },
  { id: "data-h2-02", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: 'print("python"[-2])',
    answer: "o", distractors: ["n", "p", "エラー"],
    explanation: "負のインデックスは末尾から。-1='n', -2='o'。" },
  { id: "data-h2-03", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "d = {'a': 1, 'b': 2}\nprint(list(d))",
    answer: "['a', 'b']", distractors: ["[1, 2]", "[('a', 1), ('b', 2)]", "{'a', 'b'}"],
    explanation: "辞書を list() するとキーの一覧になる。" },
  { id: "data-h2-04", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print([x for x in range(6) if x % 2])",
    answer: "[1, 3, 5]", distractors: ["[0, 2, 4]", "[1, 2, 3]", "[2, 4]"],
    explanation: "x % 2 が真(=1,3,5)の要素だけ残す内包表記。" },
  { id: "data-h2-05", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(({1, 2, 3} - {2}) == {1, 3})",
    answer: "True", distractors: ["False", "{1, 3}", "エラー"],
    explanation: "差集合 {1,2,3}-{2} は {1,3}。集合は表示順が不定なので比較で確認。" },
  /* ---- データ操作 / 最難(3) ---- */
  { id: "data-h3-01", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "a = [[0]] * 3\na[0].append(1)\nprint(a)",
    answer: "[[0, 1], [0, 1], [0, 1]]", distractors: ["[[0, 1], [0], [0]]", "[[0, 1]]", "エラー"],
    explanation: "* 3 は同じ内側リストの参照を3つ作る。1つ変えると全部変わる。" },
  { id: "data-h3-02", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "g = (x for x in [1, 2])\nprint(list(g), list(g))",
    answer: "[1, 2] []", distractors: ["[1, 2] [1, 2]", "[] []", "エラー"],
    explanation: "ジェネレータは一度消費すると空になる。2回目の list() は空。" },
  { id: "data-h3-03", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(sorted(['bb', 'a', 'ccc'], key=len))",
    answer: "['a', 'bb', 'ccc']", distractors: ["['bb', 'a', 'ccc']", "['ccc', 'bb', 'a']", "['a', 'ccc', 'bb']"],
    explanation: "key=len で文字数の昇順に並べ替える。" },
  { id: "data-h3-04", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "d = {}\nd.setdefault('k', []).append(1)\nprint(d)",
    answer: "{'k': [1]}", distractors: ["{}", "{'k': 1}", "エラー"],
    explanation: "setdefault はキーが無ければ既定値を設定して返す。返ったリストに追加。" },
  { id: "data-h3-05", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print([1, 2, 3][::-1])",
    answer: "[3, 2, 1]", distractors: ["[1, 2, 3]", "[3, 2]", "エラー"],
    explanation: "[::-1] は逆順スライス。リストを反転した新リストを返す。" },

  /* ---- プログラム構成・堅牢性 / 難(2) ---- */
  { id: "rob-h2-01", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "try:\n    int('x')\nexcept (TypeError, ValueError):\n    print('caught')",
    answer: "caught", distractors: ["x", "エラーで停止", ""],
    explanation: "複数の例外型は (A, B) とタプルでまとめて捕捉できる。" },
  { id: "rob-h2-02", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "try:\n    x = 1\nexcept Exception:\n    print('e')\nelse:\n    print('ok')",
    answer: "ok", distractors: ["e", "ok と e の両方", "何も出ない"],
    explanation: "例外が起きなかったときだけ else 節が実行される。" },
  { id: "rob-h2-03", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "try:\n    raise ValueError('a')\nexcept ValueError as e:\n    print(str(e))",
    answer: "a", distractors: ["ValueError", "e", "エラー"],
    explanation: "raise の引数が例外オブジェクト e の文字列表現になる。" },
  { id: "rob-h2-04", category: "プログラム構成・堅牢性", module: "M02", format: "fill", difficulty: 2,
    question: "ValueError と TypeError をまとめて捕捉する except 節は?", code: "try:\n    ...\nexcept ___:\n    ...",
    answer: "(ValueError, TypeError)", distractors: ["ValueError, TypeError", "ValueError | TypeError", "ValueError and TypeError"],
    explanation: "複数型は丸括弧のタプルで指定する。" },
  { id: "rob-h2-05", category: "プログラム構成・堅牢性", module: "M06", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "import math as m\nprint(m.floor(3.7))",
    answer: "3", distractors: ["4", "3.0", "エラー"],
    explanation: "import ... as で別名を付けられる。floor は切り捨てで 3。" },
  /* ---- プログラム構成・堅牢性 / 最難(3) ---- */
  { id: "rob-h3-01", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "def f():\n    try:\n        return 1\n    finally:\n        return 2\nprint(f())",
    answer: "2", distractors: ["1", "エラー", "None"],
    explanation: "finally 内の return は try の return を上書きする(要注意の挙動)。" },
  { id: "rob-h3-02", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class MyErr(Exception):\n    pass\ntry:\n    raise MyErr('x')\nexcept Exception as e:\n    print(type(e).__name__)",
    answer: "MyErr", distractors: ["Exception", "x", "エラー"],
    explanation: "自作例外も Exception で捕捉でき、型名は MyErr。" },
  { id: "rob-h3-03", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class AppErr(Exception):\n    pass\nclass DbErr(AppErr):\n    pass\ntry:\n    raise DbErr()\nexcept AppErr:\n    print('caught')",
    answer: "caught", distractors: ["エラーで停止", "DbErr", ""],
    explanation: "サブクラスの例外は親クラスの型でも捕捉できる(例外の階層)。" },
  { id: "rob-h3-04", category: "プログラム構成・堅牢性", module: "M04", format: "output", difficulty: 3,
    question: "出力を順に並べると?", code: "class C:\n    def __enter__(self):\n        print('in'); return self\n    def __exit__(self, *a):\n        print('out')\nwith C():\n    print('body')",
    answer: "in body out", distractors: ["body in out", "in out body", "body out"],
    explanation: "with は __enter__→本体→__exit__ の順。in→body→out。" },
  { id: "rob-h3-05", category: "プログラム構成・堅牢性", module: "M06", format: "output", difficulty: 3,
    question: "このファイルを直接 python3 で実行したときの出力は?", code: 'print(__name__ == "__main__")',
    answer: "True", distractors: ["False", "__main__", "エラー"],
    explanation: "直接実行時 __name__ は '__main__'。import 時は False になる。" },

  /* =====================================================================
     基礎・構文 (追加)
     ===================================================================== */
  // ===== difficulty 1 (11問: fill×3, debug×2, output×6) =====
  { id: "base-n1-01", category: "基礎・構文", module: "M00", format: "output", difficulty: 1,
    question: "出力を順に並べると?", code: "i = 0\nwhile i < 3:\n    print(i)\n    i += 1",
    answer: "0 1 2", distractors: ["1 2 3", "0 1 2 3", "0 0 0"],
    explanation: "i は 0,1,2 と進み 3 で条件 i<3 が偽になり終了する。" },

  { id: "base-n1-02", category: "基礎・構文", module: "M00", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: 'print("hello"[-1])',
    answer: "o", distractors: ["h", "hello", "-1"],
    explanation: "負のインデックス -1 は末尾の文字を指す。" },

  { id: "base-n1-03", category: "基礎・構文", module: "M00", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: 'print("cat".upper())',
    answer: "CAT", distractors: ["cat", "Cat", "CAT()"],
    explanation: "upper() は文字列をすべて大文字にする。" },

  { id: "base-n1-04", category: "基礎・構文", module: "M00", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: 'print("a" in "cat")',
    answer: "True", distractors: ["False", "1", "a"],
    explanation: "in は左の文字列が右に含まれるかを判定する。\"cat\" に \"a\" はある。" },

  { id: "base-n1-05", category: "基礎・構文", module: "M00", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: 'x = 5\nprint("big" if x > 3 else "small")',
    answer: "big", distractors: ["small", "True", "5"],
    explanation: "三項演算 A if 条件 else B。x>3 が真なので \"big\"。" },

  { id: "base-n1-06", category: "基礎・構文", module: "M00", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: 'a, b = 1, 2\nprint(a + b)',
    answer: "3", distractors: ["12", "1 2", "(1, 2)"],
    explanation: "多重代入で a=1, b=2 となり、a+b は 3。" },

  { id: "base-n1-07", category: "基礎・構文", module: "M00", format: "fill", difficulty: 1,
    question: "文字列をすべて大文字にする文字列メソッドは? (___ を埋める)", code: 'print("hi".___())',
    answer: "upper", distractors: ["toupper", "capital", "big"],
    explanation: "文字列メソッド upper() で大文字に変換する。" },

  { id: "base-n1-08", category: "基礎・構文", module: "M00", format: "fill", difficulty: 1,
    question: "条件が真の間くり返すループのキーワードは? (___ を埋める)", code: "___ i < 3:\n    i += 1",
    answer: "while", distractors: ["for", "loop", "repeat"],
    explanation: "while は条件が真である間、処理をくり返す。" },

  { id: "base-n1-09", category: "基礎・構文", module: "M00", format: "fill", difficulty: 1,
    question: "ある値が並びに「含まれない」ことを表す演算子は? (___ を埋める)", code: 'print("z" ___ "cat")',
    answer: "not in", distractors: ["is not", "!in", "out of"],
    explanation: "not in は「含まれない」を判定し、含まれなければ True を返す。" },

  { id: "base-n1-10", category: "基礎・構文", module: "M00", format: "debug", difficulty: 1,
    question: "このコードはエラーになる。正しい1行目は?", code: "for i in range(3)\n    print(i)",
    answer: "for i in range(3):", distractors: ["for i in range(3);", "for (i in range(3)):", "foreach i in range(3):"],
    explanation: "for 文の行末にはコロン : が必要。" },

  { id: "base-n1-11", category: "基礎・構文", module: "M00", format: "debug", difficulty: 1,
    question: "文字列と数値を + で連結しようとしてエラーになる。正しい書き方は?", code: 'print("count: " + 5)',
    answer: 'print("count: " + str(5))', distractors: ['print("count: " + int(5))', 'print("count: " * 5)', 'print("count: " , + 5)'],
    explanation: "文字列と数値は直接 + できない。str(5) で文字列に変換する。" },

  // ===== difficulty 2 (9問: fill×2, debug×2, output×5) =====
  { id: "base-n2-01", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(True + True)",
    answer: "2", distractors: ["True", "TrueTrue", "1"],
    explanation: "True は数値として 1 扱い。1+1=2 になる。" },

  { id: "base-n2-02", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: 'print("python"[1:4])',
    answer: "yth", distractors: ["pyt", "ytho", "yth o"],
    explanation: "スライス [1:4] は index 1,2,3 の文字。4 は含まない。" },

  { id: "base-n2-03", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "a, b = 1, 2\na, b = b, a\nprint(a, b)",
    answer: "2 1", distractors: ["1 2", "2 2", "1 1"],
    explanation: "a, b = b, a で値が入れ替わる(スワップ)。" },

  { id: "base-n2-04", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(divmod(17, 5))",
    answer: "(3, 2)", distractors: ["(2, 3)", "3 2", "(3.4, 2)"],
    explanation: "divmod(a,b) は (商, 余り) のタプルを返す。17÷5 は商3 余り2。" },

  { id: "base-n2-05", category: "基礎・構文", module: "M00", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: 'print("a", end="!")\nprint("b")',
    answer: "a!b", distractors: ["a! b", "a\nb", "ab!"],
    explanation: "end=\"!\" で改行の代わりに ! を出すため、a!b が1行で続く。" },

  { id: "base-n2-06", category: "基礎・構文", module: "M00", format: "fill", difficulty: 2,
    question: "x が 2 のとき \"two\" を出したい。空欄のキーワードは? (___ を埋める)", code: "if x == 1:\n    print('one')\n___ x == 2:\n    print('two')",
    answer: "elif", distractors: ["else if", "elseif", "else"],
    explanation: "2つ目以降の条件分岐は elif を使う。" },

  { id: "base-n2-07", category: "基礎・構文", module: "M00", format: "fill", difficulty: 2,
    question: "ループを途中で完全に抜けるキーワードは? (___ を埋める)", code: "for i in range(5):\n    if i == 3:\n        ___",
    answer: "break", distractors: ["continue", "stop", "exit"],
    explanation: "break はループ自体を抜ける。continue は次の周回へ進むだけ。" },

  { id: "base-n2-08", category: "基礎・構文", module: "M00", format: "debug", difficulty: 2,
    question: "リストの全要素を表示したいが1行目が誤っている。正しい1行目は?", code: "for i = items:\n    print(i)",
    answer: "for i in items:", distractors: ["for i == items:", "for i of items:", "foreach i in items:"],
    explanation: "for ループは for 変数 in 反復対象: と書く。= ではなく in。" },

  { id: "base-n2-09", category: "基礎・構文", module: "M00", format: "debug", difficulty: 2,
    question: "偶数だけスキップして奇数を表示したい。空欄に入るキーワードは?", code: "for i in range(5):\n    if i % 2 == 0:\n        ___\n    print(i)",
    answer: "continue", distractors: ["break", "pass", "return"],
    explanation: "continue は残りをスキップして次の周回へ進む。偶数のとき print を飛ばす。" },

  // ===== difficulty 3 (9問: output×9, 引っかけ) =====
  { id: "base-n3-01", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(2 + 3 * 2 ** 2)",
    answer: "14", distractors: ["20", "100", "26"],
    explanation: "優先順位は ** > * > +。2**2=4、3*4=12、2+12=14。" },

  { id: "base-n3-02", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(2 ** -1)",
    answer: "0.5", distractors: ["-2", "2", "0"],
    explanation: "負の指数は逆数になる。2の-1乗は 1/2 = 0.5(float)。" },

  { id: "base-n3-03", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(int(-3.7))",
    answer: "-3", distractors: ["-4", "-3.7", "3"],
    explanation: "int() は切り捨てではなく0方向への切り詰め。-3.7 は -3 になる。" },

  { id: "base-n3-04", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(1 == 1.0 == True)",
    answer: "True", distractors: ["False", "1", "1.0"],
    explanation: "連鎖比較。1==1.0 かつ 1.0==True(=1) がともに成立し True。" },

  { id: "base-n3-05", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: 'print(0 or "x")',
    answer: "x", distractors: ["True", "0", "False"],
    explanation: "or は最初の真の値を返す。0 は偽なので右の \"x\" が返る。" },

  { id: "base-n3-06", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(5 or 1 / 0)",
    answer: "5", distractors: ["エラー", "True", "0.2"],
    explanation: "短絡評価。5 が真なので右側 1/0 は評価されず例外も出ない。" },

  { id: "base-n3-07", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: 'print(round(0.5), round(1.5), round(2.5))',
    answer: "0 2 2", distractors: ["1 2 3", "0 1 2", "1 2 2"],
    explanation: "Python の round は偶数丸め(銀行丸め)。0.5→0, 1.5→2, 2.5→2。" },

  { id: "base-n3-08", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(-7 // 2)",
    answer: "-4", distractors: ["-3", "-3.5", "3"],
    explanation: "// は負の無限大方向への切り捨て(floor)。-3.5 は -4 になる。" },

  { id: "base-n3-09", category: "基礎・構文", module: "M00", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(-7 % 3)",
    answer: "2", distractors: ["-1", "1", "-2"],
    explanation: "Python の % の結果は割る数の符号に従う。-7%3 は 2(正)になる。" },

  /* =====================================================================
     関数・関数型 (追加)
     ===================================================================== */
  // ===== d1 : 15問 (fn-n1-01〜15) =====
  { id: "fn-n1-01", category: "関数・関数型", module: "M10", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "print(list(zip([1, 2, 3], ['a', 'b', 'c'])))",
    answer: "[(1, 'a'), (2, 'b'), (3, 'c')]", distractors: ["[1, 'a', 2, 'b', 3, 'c']", "[(1, 2, 3), ('a', 'b', 'c')]", "[['1a'], ['2b'], ['3c']]"],
    explanation: "zip は各リストの同じ位置の要素をタプルにまとめる。" },

  { id: "fn-n1-02", category: "関数・関数型", module: "M10", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "for i, c in enumerate(['a', 'b']):\n    print(i, c)",
    answer: "0 a\n1 b", distractors: ["1 a\n2 b", "a 0\nb 1", "0 1\na b"],
    explanation: "enumerate は (添字, 要素) を 0 から順に返す。" },

  { id: "fn-n1-03", category: "関数・関数型", module: "M10", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "print(sorted([3, 1, 2], reverse=True))",
    answer: "[3, 2, 1]", distractors: ["[1, 2, 3]", "[3, 1, 2]", "[2, 1, 3]"],
    explanation: "reverse=True で降順にソートされる。" },

  { id: "fn-n1-04", category: "関数・関数型", module: "M10", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "print(max([1, 5, 3], key=lambda x: -x))",
    answer: "1", distractors: ["5", "3", "-1"],
    explanation: "key=-x で大小が反転するので、最も小さい 1 が max になる。" },

  { id: "fn-n1-05", category: "関数・関数型", module: "M10", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "print(all([True, True, False]))",
    answer: "False", distractors: ["True", "None", "0"],
    explanation: "all は全要素が真のときだけ True。False が含まれるので False。" },

  { id: "fn-n1-06", category: "関数・関数型", module: "M10", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "print(any([0, 0, 3]))",
    answer: "True", distractors: ["False", "3", "None"],
    explanation: "any は1つでも真があれば True。3 が真なので True。" },

  { id: "fn-n1-07", category: "関数・関数型", module: "M10", format: "fill", difficulty: 1,
    question: "リスト nums を昇順に並べた新しいリストを返す組み込み関数は?",
    code: "result = ___(nums)", answer: "sorted",
    distractors: ["sort", "order", "reverse"],
    explanation: "sorted(iterable) は元を変えずソート済みの新リストを返す。" },

  { id: "fn-n1-08", category: "関数・関数型", module: "M10", format: "fill", difficulty: 1,
    question: "2つのリストを位置ごとに組にして反復したい。空欄に入る関数は?",
    code: "for a, b in ___(xs, ys):\n    print(a, b)", answer: "zip",
    distractors: ["map", "pair", "join"],
    explanation: "zip(xs, ys) で同じ位置の要素を組にして反復できる。" },

  { id: "fn-n1-09", category: "関数・関数型", module: "M10", format: "fill", difficulty: 1,
    question: "反復中に添字も一緒に欲しい。空欄に入る関数は?",
    code: "for i, x in ___(items):\n    print(i, x)", answer: "enumerate",
    distractors: ["index", "count", "range"],
    explanation: "enumerate(items) は (添字, 要素) を順に返す。" },

  { id: "fn-n1-10", category: "関数・関数型", module: "M10", format: "fill", difficulty: 1,
    question: "全要素が条件を満たすか調べる組み込み関数は?",
    code: "print(___(x > 0 for x in nums))", answer: "all",
    distractors: ["any", "every", "each"],
    explanation: "all は全要素が真のとき True を返す。" },

  { id: "fn-n1-11", category: "関数・関数型", module: "M10", format: "debug", difficulty: 1,
    question: "リストを大きい順に並べたい。正しいのは?",
    code: "nums = [3, 1, 2]\nprint(___)  # [3, 2, 1] にしたい", answer: "sorted(nums, reverse=True)",
    distractors: ["sorted(nums, desc=True)", "sorted(nums, reverse)", "sort(nums, reverse=True)"],
    explanation: "降順は sorted(..., reverse=True)。reverse はキーワード引数で True を渡す。" },

  { id: "fn-n1-12", category: "関数・関数型", module: "M10", format: "debug", difficulty: 1,
    question: "文字列の長さで並べ替えたい。正しいのは?",
    code: "words = ['bb', 'a', 'ccc']\nprint(sorted(words, ___))  # ['a','bb','ccc']", answer: "key=len",
    distractors: ["key=len()", "by=len", "sort=len"],
    explanation: "key にソート基準の関数を渡す。長さ基準は key=len(呼び出さず関数自体を渡す)。" },

  { id: "fn-n1-13", category: "関数・関数型", module: "M10", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "print(min([4, 2, 8], key=lambda x: x % 3))",
    answer: "4", distractors: ["2", "8", "1"],
    explanation: "x%3 は 4→1, 2→2, 8→2。キーが最小の 1 を持つ 4 が選ばれる。" },

  { id: "fn-n1-14", category: "関数・関数型", module: "M10", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "squares = [x * x for x in range(4)]\nprint(squares)",
    answer: "[0, 1, 4, 9]", distractors: ["[1, 4, 9, 16]", "[0, 1, 2, 3]", "[0, 2, 4, 6]"],
    explanation: "リスト内包表記で 0,1,2,3 の各2乗を集める。" },

  { id: "fn-n1-15", category: "関数・関数型", module: "M10", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "def fact(n):\n    if n == 0:\n        return 1\n    return n * fact(n - 1)\nprint(fact(4))",
    answer: "24", distractors: ["12", "10", "4"],
    explanation: "再帰で 4*3*2*1 = 24 を計算する。" },

  // ===== d2 : 9問 (fn-n2-01〜09) =====
  { id: "fn-n2-01", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "data = [('b', 2), ('a', 3), ('c', 1)]\nprint(sorted(data, key=lambda t: t[1]))",
    answer: "[('c', 1), ('b', 2), ('a', 3)]", distractors: ["[('a', 3), ('b', 2), ('c', 1)]", "[('b', 2), ('a', 3), ('c', 1)]", "[('a', 3), ('c', 1), ('b', 2)]"],
    explanation: "key=t[1] で各タプルの2番目の値(数値)を基準に昇順ソートする。" },

  { id: "fn-n2-02", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "d = {'x': 3, 'y': 1, 'z': 2}\nprint(sorted(d.items(), key=lambda kv: kv[1]))",
    answer: "[('y', 1), ('z', 2), ('x', 3)]", distractors: ["[('x', 3), ('y', 1), ('z', 2)]", "[('x', 1), ('y', 2), ('z', 3)]", "[('y', 1), ('x', 3), ('z', 2)]"],
    explanation: "items() を値 kv[1] で昇順ソート。値 1,2,3 の順に並ぶ。" },

  { id: "fn-n2-03", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "def f(*args):\n    print(args)\nf(1, 2, 3)",
    answer: "(1, 2, 3)", distractors: ["[1, 2, 3]", "1 2 3", "{1, 2, 3}"],
    explanation: "*args は受け取った位置引数をタプルにまとめる。" },

  { id: "fn-n2-04", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "def f(a, *, b):\n    return a - b\nprint(f(10, b=3))",
    answer: "7", distractors: ["13", "エラー", "-7"],
    explanation: "* の後ろ b はキーワード専用引数。b=3 と名前指定で渡す必要がある。" },

  { id: "fn-n2-05", category: "関数・関数型", module: "M10", format: "debug", difficulty: 2,
    question: "リスト nums の3要素を add の3引数として渡したい。正しいのは?",
    code: "def add(a, b, c):\n    return a + b + c\nnums = [1, 2, 3]\nprint(add(___))  # 6 にしたい", answer: "*nums",
    distractors: ["nums", "**nums", "nums[:]"],
    explanation: "f(*nums) は呼び出し時にリストを展開し a=1,b=2,c=3 として渡す。" },

  { id: "fn-n2-06", category: "関数・関数型", module: "M10", format: "debug", difficulty: 2,
    question: "辞書 d をキーワード引数として greet に渡したい。正しいのは?",
    code: "def greet(name, msg):\n    return msg + ', ' + name\nd = {'name': 'Bob', 'msg': 'Hi'}\nprint(greet(___))  # 'Hi, Bob'", answer: "**d",
    distractors: ["*d", "d", "d.values()"],
    explanation: "f(**d) は辞書のキーを引数名に対応させて展開して渡す。" },

  { id: "fn-n2-07", category: "関数・関数型", module: "M10", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "def make_adder(n):\n    def add(x):\n        return x + n\n    return add\nadd5 = make_adder(5)\nprint(add5(3))",
    answer: "8", distractors: ["5", "3", "15"],
    explanation: "引数つきクロージャ。make_adder(5) が返す関数は n=5 を覚えており、3+5=8。" },

  { id: "fn-n2-08", category: "関数・関数型", module: "M10", format: "fill", difficulty: 2,
    question: "関数 f に常に 10 を第1引数として渡す新しい関数を作りたい。空欄は?",
    code: "from functools import ___\nadd10 = ___(f, 10)", answer: "partial",
    distractors: ["reduce", "wraps", "lru_cache"],
    explanation: "functools.partial(f, 10) は一部の引数を固定した新関数を作る。" },

  { id: "fn-n2-09", category: "関数・関数型", module: "M10", format: "fill", difficulty: 2,
    question: "1から4までの積を畳み込みで求めたい。空欄に入る関数は?",
    code: "from functools import reduce\nprint(___(lambda a, b: a * b, [1, 2, 3, 4]))", answer: "reduce",
    distractors: ["map", "filter", "sum"],
    explanation: "reduce は左から順に2要素ずつ畳み込む。1*2*3*4=24。" },

  // ===== d3 : 9問 (fn-n3-01〜09) =====
  { id: "fn-n3-01", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "fs = [lambda i=i: i for i in range(3)]\nprint(fs[0]())",
    answer: "0", distractors: ["2", "3", "None"],
    explanation: "デフォルト引数 i=i で定義時の i を束縛するため、遅延束縛を回避できる。" },

  { id: "fn-n3-02", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "g = (x for x in range(3))\nprint(sum(g))\nprint(sum(g))",
    answer: "3\n0", distractors: ["3\n3", "6\n6", "3\nエラー"],
    explanation: "ジェネレータは一度使い切ると枯れる。2回目の sum は空で 0。" },

  { id: "fn-n3-03", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print(list(zip([1, 2, 3], ['a', 'b'])))",
    answer: "[(1, 'a'), (2, 'b')]", distractors: ["[(1, 'a'), (2, 'b'), (3, None)]", "[(1, 'a'), (2, 'b'), (3, '')]", "エラー"],
    explanation: "zip は短い方に合わせて打ち切るので、3 は捨てられる。" },

  { id: "fn-n3-04", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "from functools import reduce\nprint(reduce(lambda a, b: a + b, [1, 2, 3], 100))",
    answer: "106", distractors: ["6", "100", "103"],
    explanation: "reduce の第3引数 100 は初期値。100+1+2+3=106。" },

  { id: "fn-n3-05", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "r = map(lambda x: x * 2, [1, 2, 3])\nprint(list(r))\nprint(list(r))",
    answer: "[2, 4, 6]\n[]", distractors: ["[2, 4, 6]\n[2, 4, 6]", "[1, 2, 3]\n[]", "[2, 4, 6]\nエラー"],
    explanation: "map はイテレータを返すので、一度 list 化すると2回目は空になる。" },

  { id: "fn-n3-06", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "from functools import partial\npow2 = partial(pow, 2)\nprint(pow2(5))",
    answer: "32", distractors: ["25", "10", "7"],
    explanation: "partial(pow, 2) は pow の第1引数を 2 に固定。pow(2, 5)=32。" },

  { id: "fn-n3-07", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "g = (x * x for x in range(5))\nprint(next(g))\nprint(next(g))",
    answer: "0\n1", distractors: ["0\n0", "1\n4", "0\n1\n4"],
    explanation: "next はジェネレータを1つずつ進める。0の2乗、1の2乗の順。" },

  { id: "fn-n3-08", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "print((lambda *a: a)(1, 2, 3))",
    answer: "(1, 2, 3)", distractors: ["[1, 2, 3]", "6", "1"],
    explanation: "lambda *a:a は受け取った全引数をタプルにして返す。" },

  { id: "fn-n3-09", category: "関数・関数型", module: "M10", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "def gen():\n    yield 1\n    yield 2\n    yield 3\nprint(list(gen()))",
    answer: "[1, 2, 3]", distractors: ["[3]", "1", "<generator object>"],
    explanation: "yield する関数はジェネレータを返し、list で全値を取り出せる。" },

  /* =====================================================================
     OOP (追加)
     ===================================================================== */
  // ===== d1 (15問): 1概念直球 =====
  // --- d1 fill (5) ---
  { id: "oop-n1-01", category: "OOP", module: "M01", format: "fill", difficulty: 1,
    question: "obj が指定クラスのインスタンスか調べる組み込み関数は?",
    code: "if ___(x, int):\n    ...",
    answer: "isinstance", distractors: ["typeof", "instanceof", "issubclass"],
    explanation: "isinstance(obj, クラス) で、そのクラス(または子クラス)のインスタンスか判定する。" },
  { id: "oop-n1-02", category: "OOP", module: "M01", format: "fill", difficulty: 1,
    question: "あるクラスが別クラスのサブクラスか調べる組み込み関数は?",
    code: "if ___(B, A):\n    ...",
    answer: "issubclass", distractors: ["isinstance", "subclassof", "is_subclass"],
    explanation: "issubclass(子, 親) でクラス同士の継承関係を判定する。引数はインスタンスでなくクラス。" },
  { id: "oop-n1-03", category: "OOP", module: "M05", format: "fill", difficulty: 1,
    question: "self を取らずクラスに属する関数を定義するデコレータは?",
    code: "class M:\n    ___\n    def add(a, b):\n        return a + b",
    answer: "@staticmethod", distractors: ["@classmethod", "@property", "@static"],
    explanation: "@staticmethod は self も cls も受け取らない。クラスに属する普通の関数として使う。" },
  { id: "oop-n1-04", category: "OOP", module: "M05", format: "fill", difficulty: 1,
    question: "print() ではなく開発者向けの厳密な文字列表現を定義する特殊メソッドは?",
    answer: "__repr__", distractors: ["__str__", "__name__", "__doc__"],
    explanation: "__repr__ は repr() やリスト内表示で使われる開発者向け表現。__str__ は print 向け。" },
  { id: "oop-n1-05", category: "OOP", module: "M05", format: "fill", difficulty: 1,
    question: "len(obj) で呼ばれる、長さを定義する特殊メソッドは?",
    code: "class Box:\n    def ___(self):\n        return 3",
    answer: "__len__", distractors: ["__size__", "__length__", "__count__"],
    explanation: "len(obj) は obj.__len__() を呼ぶ。整数を返すように定義する。" },

  // --- d1 debug (4) ---
  { id: "oop-n1-06", category: "OOP", module: "M07", format: "debug", difficulty: 1,
    question: "+ 演算子を自作したい。正しい特殊メソッド名は?",
    code: "class V:\n    def ___(self, o):\n        return V(self.n + o.n)",
    answer: "__add__", distractors: ["__plus__", "__sum__", "add"],
    explanation: "a + b は a.__add__(b) を呼ぶ。演算子オーバーロードは __add__ で定義する。" },
  { id: "oop-n1-07", category: "OOP", module: "M07", format: "debug", difficulty: 1,
    question: "インスタンスを関数のように obj() と呼べるようにしたい。正しいのは?",
    code: "class F:\n    def ___(self):\n        return 'ok'",
    answer: "__call__", distractors: ["__run__", "__invoke__", "__exec__"],
    explanation: "obj() は obj.__call__() を呼ぶ。__call__ を定義するとインスタンスを呼び出せる。" },
  { id: "oop-n1-08", category: "OOP", module: "M05", format: "debug", difficulty: 1,
    question: "@staticmethod のメソッド定義が誤っている。正しいのは?",
    code: "class M:\n    @staticmethod\n    def f(self):\n        return 1",
    answer: "def f():", distractors: ["def f(self):", "def f(cls):", "static def f():"],
    explanation: "@staticmethod は self も cls も取らない。引数は呼び出し側が渡すものだけ。" },
  { id: "oop-n1-09", category: "OOP", module: "M01", format: "debug", difficulty: 1,
    question: "属性が無くてもデフォルト値が欲しい。例外を出さず取得する正しい書き方は?",
    code: "value = ___(obj, 'x', 0)",
    answer: "getattr", distractors: ["hasattr", "obj.get", "getattribute"],
    explanation: "getattr(obj, '名前', デフォルト) は属性が無ければデフォルトを返す。hasattr は真偽値のみ。" },

  // --- d1 output (6) ---
  { id: "oop-n1-10", category: "OOP", module: "M01", format: "output", difficulty: 1,
    question: "次のコードの出力は?",
    code: "class A: pass\nclass B(A): pass\nprint(isinstance(B(), A))",
    answer: "True", distractors: ["False", "B", "エラー"],
    explanation: "B は A の子クラスなので、B のインスタンスは isinstance で A とみなされ True。" },
  { id: "oop-n1-11", category: "OOP", module: "M05", format: "output", difficulty: 1,
    question: "次のコードの出力は?",
    code: "class Dog:\n    pass\nprint(type(Dog()).__name__)",
    answer: "Dog", distractors: ["type", "Dog()", "object"],
    explanation: "type(obj) はクラスを返し、その .__name__ でクラス名の文字列 'Dog' が得られる。" },
  { id: "oop-n1-12", category: "OOP", module: "M05", format: "output", difficulty: 1,
    question: "次のコードの出力は?",
    code: "class M:\n    @staticmethod\n    def add(a, b):\n        return a + b\nprint(M.add(2, 3))",
    answer: "5", distractors: ["23", "エラー", "None"],
    explanation: "@staticmethod は self を取らない普通の関数。M.add(2,3) は 2+3=5。" },
  { id: "oop-n1-13", category: "OOP", module: "M07", format: "output", difficulty: 1,
    question: "次のコードの出力は?",
    code: "class B:\n    def __len__(self):\n        return 4\nprint(len(B()))",
    answer: "4", distractors: ["1", "0", "エラー"],
    explanation: "len(obj) は obj.__len__() を呼ぶ。ここでは 4 を返す。" },
  { id: "oop-n1-14", category: "OOP", module: "M07", format: "output", difficulty: 1,
    question: "次のコードの出力は?",
    code: "class F:\n    def __call__(self):\n        return 'called'\nf = F()\nprint(f())",
    answer: "called", distractors: ["F", "<F object>", "エラー"],
    explanation: "__call__ を定義するとインスタンスを f() のように呼べる。戻り値は 'called'。" },
  { id: "oop-n1-15", category: "OOP", module: "M01", format: "output", difficulty: 1,
    question: "次のコードの出力は?",
    code: "class C:\n    x = 1\nprint(hasattr(C(), 'x'), getattr(C(), 'y', 9))",
    answer: "True 9", distractors: ["True None", "False 9", "1 9"],
    explanation: "hasattr は属性の有無を真偽で返し x は有るので True。getattr は無い y にデフォルト 9 を返す。" },

  // ===== d2 (9問): 2概念 or 典型ミス =====
  // --- d2 fill (0 here, already 5 in d1) ---
  // --- debug ---
  { id: "oop-n2-01", category: "OOP", module: "M07", format: "debug", difficulty: 2,
    question: "== の比較方法を自作したい。正しい特殊メソッドの定義は?",
    code: "class P:\n    def __init__(self, n):\n        self.n = n\n    def ___(self, o):\n        return self.n == o.n",
    answer: "__eq__", distractors: ["__equals__", "__cmp__", "__is__"],
    explanation: "a == b は a.__eq__(b) を呼ぶ。等値比較のカスタマイズは __eq__ で行う。" },
  // --- output ---
  { id: "oop-n2-02", category: "OOP", module: "M07", format: "output", difficulty: 2,
    question: "次のコードの出力は?",
    code: "class V:\n    def __init__(self, n):\n        self.n = n\n    def __add__(self, o):\n        return V(self.n + o.n)\nr = V(1) + V(2) + V(3)\nprint(r.n)",
    answer: "6", distractors: ["123", "5", "エラー"],
    explanation: "__add__ が V を返すので連鎖できる。((1+2)+3)=6。" },
  { id: "oop-n2-03", category: "OOP", module: "M05", format: "output", difficulty: 2,
    question: "次のコードの出力は?",
    code: "class T:\n    def __init__(self):\n        self._v = 0\n    @property\n    def v(self):\n        return self._v\n    @v.setter\n    def v(self, x):\n        self._v = x * 2\nt = T()\nt.v = 5\nprint(t.v)",
    answer: "10", distractors: ["5", "0", "エラー"],
    explanation: "setter が x*2 を格納するので t.v=5 で _v=10。getter はそれをそのまま返す。" },
  { id: "oop-n2-04", category: "OOP", module: "M05", format: "output", difficulty: 2,
    question: "次のコードの出力は?",
    code: "class P:\n    def __str__(self):\n        return 'X'\n    def __repr__(self):\n        return 'Y'\nprint(f'{P()}')",
    answer: "X", distractors: ["Y", "P", "<P object>"],
    explanation: "f文字列の {obj} は str() 経由なので __str__ が使われ 'X'。__repr__ は使われない。" },
  { id: "oop-n2-05", category: "OOP", module: "M07", format: "output", difficulty: 2,
    question: "次のコードの出力は?",
    code: "class E:\n    def __len__(self):\n        return 0\nprint(bool(E()))",
    answer: "False", distractors: ["True", "0", "エラー"],
    explanation: "真偽判定は __len__ が 0 を返すと偽とみなされる。よって bool(E()) は False。" },
  { id: "oop-n2-06", category: "OOP", module: "M07", format: "output", difficulty: 2,
    question: "次のコードの出力は?",
    code: "class Duck:\n    def sound(self):\n        return 'quack'\nclass Dog:\n    def sound(self):\n        return 'woof'\ndef speak(a):\n    return a.sound()\nprint(speak(Duck()), speak(Dog()))",
    answer: "quack woof", distractors: ["quack quack", "woof woof", "エラー"],
    explanation: "ダックタイピング: 同じ sound() を持てば型に関係なく呼べる。それぞれの戻り値が出る。" },
  { id: "oop-n2-07", category: "OOP", module: "M01", format: "output", difficulty: 2,
    question: "次のコードの出力は?",
    code: "class C:\n    def hi(self):\n        return 'hi'\nc = C()\nprint(C.hi(c))",
    answer: "hi", distractors: ["エラー", "<bound method>", "None"],
    explanation: "クラス経由 C.hi(c) はインスタンスを self として手動で渡す呼び方。c.hi() と等価。" },
  { id: "oop-n2-08", category: "OOP", module: "M01", format: "output", difficulty: 2,
    question: "次のコードの出力は?",
    code: "class A:\n    def __init__(self):\n        self.x = 1\nclass B(A):\n    def __init__(self):\n        self.y = 2\nb = B()\nprint(hasattr(b, 'x'))",
    answer: "False", distractors: ["True", "1", "エラー"],
    explanation: "子の __init__ を定義すると親 __init__ は自動では呼ばれない。x は作られず False。" },
  { id: "oop-n2-09", category: "OOP", module: "M01", format: "output", difficulty: 2,
    question: "次のコードの出力は?",
    code: "class A:\n    def __init__(self):\n        self.log = 'A'\nclass B(A):\n    def __init__(self):\n        super().__init__()\n        self.log += 'B'\nprint(B().log)",
    answer: "AB", distractors: ["A", "B", "BA"],
    explanation: "super().__init__() で親が log='A' を設定し、その後 'B' を足して 'AB'。" },

  // ===== d3 (9問): 引っかけ =====
  // --- output ---
  { id: "oop-n3-01", category: "OOP", module: "M07", format: "output", difficulty: 3,
    question: "次のコードの出力は?",
    code: "class C:\n    items = []\n    def add(self, v):\n        self.items.append(v)\na = C()\nb = C()\na.add(1)\nb.add(2)\nprint(b.items)",
    answer: "[1, 2]", distractors: ["[2]", "[1]", "[]"],
    explanation: "リストをクラス変数にすると全インスタンスで共有される。a と b の append が同じリストに入る。" },
  { id: "oop-n3-02", category: "OOP", module: "M05", format: "output", difficulty: 3,
    question: "出力を順に並べると?",
    code: "class P:\n    def __str__(self):\n        return 'S'\n    def __repr__(self):\n        return 'R'\np = P()\nprint(p)\nprint([p])",
    answer: "S [R]", distractors: ["S [S]", "R [R]", "S S"],
    explanation: "print(obj) は __str__ で 'S'、リスト内の要素は __repr__ で表示され '[R]'。" },
  { id: "oop-n3-03", category: "OOP", module: "M05", format: "output", difficulty: 3,
    question: "出力を順に並べると?",
    code: "class P:\n    def __repr__(self):\n        return 'R'\np = P()\nprint(p)\nprint([p])",
    answer: "R [R]", distractors: ["S [R]", "<P> [R]", "R R"],
    explanation: "__str__ が無いと print も __repr__ にフォールバックする。両方とも 'R'。" },
  { id: "oop-n3-04", category: "OOP", module: "M01", format: "output", difficulty: 3,
    question: "次のコードの出力は?",
    code: "class C:\n    x = 1\nc = C()\nc.x = 99\nprint(C.x)",
    answer: "1", distractors: ["99", "100", "エラー"],
    explanation: "c.x=99 はインスタンス属性を新設してクラス変数を隠すだけ。クラス側 C.x は 1 のまま。" },
  { id: "oop-n3-05", category: "OOP", module: "M01", format: "output", difficulty: 3,
    question: "出力を順に並べると?",
    code: "class C:\n    n = 10\nc = C()\nc.n += 5\nprint(c.n, C.n)",
    answer: "15 10", distractors: ["15 15", "10 10", "15 5"],
    explanation: "c.n += 5 は読み(クラス変数10)→インスタンス属性へ代入。c.n=15 だが C.n は 10 のまま。" },
  { id: "oop-n3-06", category: "OOP", module: "M07", format: "output", difficulty: 3,
    question: "出力を順に並べると?",
    code: "class P:\n    def __init__(self, n):\n        self.n = n\n    def __eq__(self, o):\n        return self.n == o.n\nprint(P(1) == P(1), P(1) is P(1))",
    answer: "True False", distractors: ["True True", "False False", "False True"],
    explanation: "__eq__ で == は値比較 True。is は同一オブジェクト判定で別物なので False。" },
  { id: "oop-n3-07", category: "OOP", module: "M05", format: "output", difficulty: 3,
    question: "次のコードの出力は?",
    code: "class T:\n    @property\n    def v(self):\n        return 1\nt = T()\nt.v = 5\nprint(t.v)",
    answer: "エラー", distractors: ["5", "1", "10"],
    explanation: "setter の無い @property に代入すると AttributeError(has no setter)になる。" },
  { id: "oop-n3-08", category: "OOP", module: "M05", format: "output", difficulty: 3,
    question: "次のコードの出力は?",
    code: "from abc import ABC, abstractmethod\nclass Base(ABC):\n    @abstractmethod\n    def run(self):\n        ...\nBase()",
    answer: "エラー", distractors: ["None", "Base", "run"],
    explanation: "抽象メソッド未実装のまま ABC を継承したクラスは生成できず TypeError になる。" },
  { id: "oop-n3-09", category: "OOP", module: "M07", format: "output", difficulty: 3,
    question: "次のコードの出力は?",
    code: "class N:\n    def __init__(self, v):\n        self.v = v\n    def __add__(self, o):\n        return self.v + o\nprint(N(3) + 4)",
    answer: "7", distractors: ["N", "34", "エラー"],
    explanation: "__add__ の右辺は整数でもよい。self.v(3)+o(4)=7。返り値は素の整数。" },

  /* =====================================================================
     データ操作 (追加)
     ===================================================================== */
  // ===== d1 (14問: data-n1-01〜14) =====
  { id: "data-n1-01", category: "データ操作", module: "M03", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "a = [1, 2]\na.extend([3, 4])\nprint(a)",
    answer: "[1, 2, 3, 4]", distractors: ["[1, 2, [3, 4]]", "[3, 4, 1, 2]", "[1, 2, 3, 4, 3, 4]"],
    explanation: "extend は引数の各要素を末尾に連結する。append はリストごと追加する。" },

  { id: "data-n1-02", category: "データ操作", module: "M03", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "a = [1, 2, 3]\na.insert(1, 9)\nprint(a)",
    answer: "[1, 9, 2, 3]", distractors: ["[9, 1, 2, 3]", "[1, 2, 9, 3]", "[1, 2, 3, 9]"],
    explanation: "insert(i, x) は index i の位置に x を割り込ませ、以降を後ろへずらす。" },

  { id: "data-n1-03", category: "データ操作", module: "M03", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "a = [1, 2, 3]\nprint(a.pop())",
    answer: "3", distractors: ["1", "[1, 2]", "None"],
    explanation: "list.pop() は引数なしで末尾要素を取り除き、その値を返す。" },

  { id: "data-n1-04", category: "データ操作", module: "M03", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "a = [10, 20, 30]\nprint(a.index(20))",
    answer: "1", distractors: ["20", "2", "0"],
    explanation: "index(x) は x が最初に現れる位置(index)を返す。値ではない。" },

  { id: "data-n1-05", category: "データ操作", module: "M03", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "d = {'a': 1, 'b': 2}\nprint(list(d.values()))",
    answer: "[1, 2]", distractors: ["['a', 'b']", "[('a', 1), ('b', 2)]", "{1, 2}"],
    explanation: "values() は値のビューを返す。list() で値のリストになる。" },

  { id: "data-n1-06", category: "データ操作", module: "M03", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "d = {'a': 1}\nd.update({'b': 2})\nprint(d)",
    answer: "{'a': 1, 'b': 2}", distractors: ["{'a': 1}", "{'b': 2}", "{'a': 1, 'b': 2, 'b': 2}"],
    explanation: "update は別の辞書のキー/値をまとめて取り込む。挿入順で表示される。" },

  { id: "data-n1-07", category: "データ操作", module: "M03", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "print(''.join(['a', 'b', 'c']))",
    answer: "abc", distractors: ["['a', 'b', 'c']", "a b c", "a,b,c"],
    explanation: "区切り文字.join(リスト) で文字列を連結する。空文字なら区切りなし。" },

  { id: "data-n1-08", category: "データ操作", module: "M03", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "print(dict(zip(['a', 'b'], [1, 2])))",
    answer: "{'a': 1, 'b': 2}", distractors: ["{'a': 'b', 1: 2}", "[('a', 1), ('b', 2)]", "{1: 'a', 2: 'b'}"],
    explanation: "zip でキーと値を対にし、dict() に渡すと辞書になる。" },

  { id: "data-n1-09", category: "データ操作", module: "M03", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "a, b, c = (1, 2, 3)\nprint(b)",
    answer: "2", distractors: ["1", "3", "(1, 2, 3)"],
    explanation: "タプルアンパックで左辺の各変数に順に代入される。b は 2 番目の要素。" },

  { id: "data-n1-10", category: "データ操作", module: "M03", format: "output", difficulty: 1,
    question: "出力を順に並べると?", code: "for i, v in enumerate(['a', 'b']):\n    print(i, v)",
    answer: "0 a 1 b", distractors: ["1 a 2 b", "a 0 b 1", "0 1 a b"],
    explanation: "enumerate は (index, 要素) を順に返す。既定の開始は 0。" },

  { id: "data-n1-11", category: "データ操作", module: "M03", format: "fill", difficulty: 1,
    question: "リストの全要素を別のリストの末尾に連結する(1つずつ追加する)メソッドは?",
    code: "a = [1, 2]\na.___([3, 4])  # -> [1, 2, 3, 4]",
    answer: "extend", distractors: ["append", "insert", "join"],
    explanation: "extend は要素を1つずつ連結。append([3,4]) だと [3,4] ごと1要素として入る。" },

  { id: "data-n1-12", category: "データ操作", module: "M03", format: "fill", difficulty: 1,
    question: "辞書からキーと値のペアをまとめて取り出すメソッドは?",
    code: "d = {'a': 1}\nfor k, v in d.___():\n    print(k, v)",
    answer: "items", distractors: ["keys", "values", "pairs"],
    explanation: "items() は (キー, 値) のタプルを順に返す。keys() はキー、values() は値のみ。" },

  { id: "data-n1-13", category: "データ操作", module: "M03", format: "fill", difficulty: 1,
    question: "リスト末尾の要素を取り除いてその値を返すメソッドは?",
    code: "a = [1, 2, 3]\nx = a.___()  # x は 3、a は [1, 2]",
    answer: "pop", distractors: ["remove", "del", "discard"],
    explanation: "pop() は末尾(または index 指定)を取り除き値を返す。remove(値) は値を指定して削除し戻り値なし。" },

  { id: "data-n1-14", category: "データ操作", module: "M03", format: "debug", difficulty: 1,
    question: "リストから値 2 を1つ削除したい。正しい行は?",
    code: "a = [1, 2, 3]\n# a から 2 を削除したい",
    answer: "a.remove(2)", distractors: ["a.delete(2)", "a.pop(2)", "del a(2)"],
    explanation: "remove(値) は指定値を1つ削除。pop(2) は index 2 の要素を消すので意味が違う。" },

  // ===== d2 (9問: data-n2-01〜09) =====
  { id: "data-n2-01", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(({1, 2} | {2, 3}) == {1, 2, 3})",
    answer: "True", distractors: ["False", "{1, 2, 3}", "{1, 2, 2, 3}"],
    explanation: "| は和集合。{1,2} と {2,3} の和は {1,2,3} なので等しく True。" },

  { id: "data-n2-02", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(({1, 2, 3} & {2, 3, 4}) == {2, 3})",
    answer: "True", distractors: ["False", "{2, 3}", "{1, 4}"],
    explanation: "& は積集合(共通要素)。共通は {2,3} なので True。" },

  { id: "data-n2-03", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print(({1, 2} ^ {2, 3}) == {1, 3})",
    answer: "True", distractors: ["False", "{1, 3}", "{2}"],
    explanation: "^ は対称差(片方だけにある要素)。1 と 3 が残り {1,3} なので True。" },

  { id: "data-n2-04", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "a = [1, 2, 3, 4]\na[1:3] = [9]\nprint(a)",
    answer: "[1, 9, 4]", distractors: ["[1, 9, 3, 4]", "[1, [9], 4]", "[1, 9, 9, 4]"],
    explanation: "スライス代入は範囲ごと差し替える。2要素を1要素に置き換えるので長さが縮む。" },

  { id: "data-n2-05", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "d = {'a': 1, 'b': 2}\nprint(d.pop('a'))",
    answer: "1", distractors: ["'a'", "{'b': 2}", "None"],
    explanation: "dict.pop(キー) はそのキーを削除し、対応する値を返す。" },

  { id: "data-n2-06", category: "データ操作", module: "M03", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "print([1, 2, 3, 4][10:])",
    answer: "[]", distractors: ["[4]", "エラー", "None"],
    explanation: "範囲外のスライスは例外にならず空リストを返す。インデックス単体だと IndexError。" },

  { id: "data-n2-07", category: "データ操作", module: "M03", format: "fill", difficulty: 2,
    question: "リストから index 1 の要素そのものを削除する文は?",
    code: "a = [1, 2, 3]\n___ a[1]  # -> [1, 3]",
    answer: "del", distractors: ["pop", "remove", "drop"],
    explanation: "del a[1] は文で、指定位置の要素を削除する。a.pop(1) でも可だが remove は値指定。" },

  { id: "data-n2-08", category: "データ操作", module: "M03", format: "fill", difficulty: 2,
    question: "集合 s が {1,2,3} の部分集合かを判定するメソッドは?",
    code: "s = {1, 2}\nprint(s.___({1, 2, 3}))  # -> True",
    answer: "issubset", distractors: ["issuperset", "contains", "subset"],
    explanation: "issubset は自身が引数集合に含まれるかを返す。逆向きは issuperset。" },

  { id: "data-n2-09", category: "データ操作", module: "M03", format: "debug", difficulty: 2,
    question: "辞書 d にキー 'b' がある時だけ True にしたい。in は何を見る?",
    code: "d = {'a': 1, 'b': 2}\n# 'b' があるか調べる正しい式は?",
    answer: "'b' in d", distractors: ["2 in d", "'b' in d.values()", "d.has('b')"],
    explanation: "dict に対する in は『キー』の存在を調べる。値を見るなら in d.values()。" },

  // ===== d3 (9問: data-n3-01〜09) 引っかけ =====
  { id: "data-n3-01", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "a = [[1], [2]]\nb = a[:]\nb[0].append(9)\nprint(a)",
    answer: "[[1, 9], [2]]", distractors: ["[[1], [2]]", "[[1, 9], [2, 9]]", "[[9], [2]]"],
    explanation: "b = a[:] は浅いコピー。外側は別物だが内側のリストは共有され、変更が a にも及ぶ。" },

  { id: "data-n3-02", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "x = [3, 1, 2].sort()\nprint(x)",
    answer: "None", distractors: ["[1, 2, 3]", "[3, 1, 2]", "エラー"],
    explanation: "list.sort() はその場で並べ替えて None を返す。並べた結果が欲しいなら sorted()。" },

  { id: "data-n3-03", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "d = dict.fromkeys(['a', 'b'], [])\nd['a'].append(1)\nprint(d)",
    answer: "{'a': [1], 'b': [1]}", distractors: ["{'a': [1], 'b': []}", "{'a': [], 'b': []}", "{'a': 1, 'b': 1}"],
    explanation: "fromkeys の既定値は全キーで同一オブジェクトを共有する。片方の変更が両方に出る。" },

  { id: "data-n3-04", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "d = {'a': 3, 'b': 1, 'c': 2}\nprint(sorted(d, key=d.get))",
    answer: "['b', 'c', 'a']", distractors: ["['a', 'b', 'c']", "[1, 2, 3]", "['a', 'c', 'b']"],
    explanation: "sorted(d) はキーを反復し、key=d.get で値を基準に並べる。値1,2,3 の順に b,c,a。" },

  { id: "data-n3-05", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "t = ([1],)\ntry:\n    t[0] += [2]\nexcept TypeError:\n    pass\nprint(t)",
    answer: "([1, 2],)", distractors: ["([1],)", "([1, 2])", "エラー"],
    explanation: "t[0] += [2] は中身を拡張(成功)した後に再代入で TypeError。変更は反映され ([1,2],) になる。" },

  { id: "data-n3-06", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "a, (b, c) = 1, (2, 3)\nprint(c)",
    answer: "3", distractors: ["2", "1", "(2, 3)"],
    explanation: "ネストしたアンパック。右の (2,3) が (b,c) に分配され c は 3。" },

  { id: "data-n3-07", category: "データ操作", module: "M03", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "a = [1, 2, 3]\na[::2] = [7, 9]\nprint(a)",
    answer: "[7, 2, 9]", distractors: ["[7, 9, 3]", "[1, 7, 9]", "[7, 2, 9, 3]"],
    explanation: "拡張スライス代入は1つおき(index 0 と 2)を置き換える。要素数が一致する必要がある。" },

  { id: "data-n3-08", category: "データ操作", module: "M03", format: "debug", difficulty: 3,
    question: "[3,1,2] を昇順に並べた新しいリストを得たい。x が None になる誤りはどれ?",
    code: "nums = [3, 1, 2]\nx = nums.____  # x にソート結果を入れたい",
    answer: "x = nums.sort()", distractors: ["x = sorted(nums)", "x = sorted(nums, reverse=False)", "x = nums.copy(); x.sort()"],
    explanation: "sort() は in-place で None を返す。新リストが欲しいなら sorted() を使う。" },

  { id: "data-n3-09", category: "データ操作", module: "M03", format: "debug", difficulty: 3,
    question: "2次元グリッドを作る。全行が連動してしまう誤った初期化はどれ?",
    code: "# 3行2列を 0 で初期化したい\ngrid = ____",
    answer: "[[0] * 2] * 3", distractors: ["[[0] * 2 for _ in range(3)]", "[[0, 0] for _ in range(3)]", "[[0, 0], [0, 0], [0, 0]]"],
    explanation: "[行]*3 は同じ内側リストを3回参照する。1行への代入が全行に波及する。内包表記なら独立。" },

  /* =====================================================================
     プログラム構成・堅牢性 (追加)
     ===================================================================== */
  // ===== d1 (14問) rob-n1-01〜14 =====
  { id: "rob-n1-01", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "try:\n    x = int('10')\nexcept ValueError:\n    x = -1\nprint(x)",
    answer: "10", distractors: ["-1", "エラー", "None"],
    explanation: "int('10') は成功するので except は通らず x=10。" },

  { id: "rob-n1-02", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "d = {'a': 1}\ntry:\n    print(d['b'])\nexcept KeyError:\n    print('no key')",
    answer: "no key", distractors: ["1", "None", "エラー"],
    explanation: "存在しないキー 'b' で KeyError が起き except が処理する。" },

  { id: "rob-n1-03", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "assert 1 + 1 == 2\nprint('ok')",
    answer: "ok", distractors: ["True", "エラー", "2"],
    explanation: "assert の条件が真なら何も起きず、続けて 'ok' が出力される。" },

  { id: "rob-n1-04", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "x = -3\ntry:\n    assert x > 0\nexcept AssertionError:\n    print('fail')",
    answer: "fail", distractors: ["ok", "エラー", "-3"],
    explanation: "x>0 が偽なので AssertionError が起き except が 'fail' を出力。" },

  { id: "rob-n1-05", category: "プログラム構成・堅牢性", module: "M02", format: "fill", difficulty: 1,
    question: "条件が偽のとき AssertionError を発生させる文のキーワードは?", code: "___ x > 0, 'x must be positive'",
    answer: "assert", distractors: ["raise", "check", "verify"],
    explanation: "assert 条件, メッセージ で条件が偽のとき例外を発生させる。" },

  { id: "rob-n1-06", category: "プログラム構成・堅牢性", module: "M06", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "from math import pi\nprint(round(pi, 2))",
    answer: "3.14", distractors: ["3.0", "3.1415", "3"],
    explanation: "from math import pi で pi を取り込み、小数2桁に丸めると 3.14。" },

  { id: "rob-n1-07", category: "プログラム構成・堅牢性", module: "M06", format: "fill", difficulty: 1,
    question: "import したモジュールに別名を付けるキーワードは?", code: "import numpy ___ np",
    answer: "as", distractors: ["alias", "to", "name"],
    explanation: "import モジュール as 別名 で短い名前を付けられる。" },

  { id: "rob-n1-08", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "try:\n    raise KeyError('k')\nexcept KeyError:\n    print('caught')",
    answer: "caught", distractors: ["k", "KeyError", "エラー"],
    explanation: "raise した KeyError を同じ型の except が捕捉して 'caught' を出力。" },

  { id: "rob-n1-09", category: "プログラム構成・堅牢性", module: "M02", format: "fill", difficulty: 1,
    question: "ファイルが見つからないときに発生する例外名は?",
    answer: "FileNotFoundError", distractors: ["IOError", "FileError", "NotFoundError"],
    explanation: "存在しないファイルを open すると FileNotFoundError が発生する。" },

  { id: "rob-n1-10", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "try:\n    raise ValueError('bad')\nexcept ValueError as e:\n    print(e.args[0])",
    answer: "bad", distractors: ["('bad',)", "ValueError", "エラー"],
    explanation: "e.args は引数のタプルで、その先頭 e.args[0] は 'bad'。" },

  { id: "rob-n1-11", category: "プログラム構成・堅牢性", module: "M06", format: "output", difficulty: 1,
    question: "次のコードの出力は?", code: "import math\nprint(math.gcd(12, 8))",
    answer: "4", distractors: ["2", "24", "96"],
    explanation: "12 と 8 の最大公約数は 4。" },

  { id: "rob-n1-12", category: "プログラム構成・堅牢性", module: "M02", format: "fill", difficulty: 1,
    question: "with 文でファイルを開くと、ブロック終了時に自動で呼ばれて閉じてくれる仕組みを何と呼ぶ?",
    answer: "コンテキストマネージャ", distractors: ["イテレータ", "デコレータ", "ジェネレータ"],
    explanation: "with 文が利用するのはコンテキストマネージャで、終了時に自動で後始末する。" },

  { id: "rob-n1-13", category: "プログラム構成・堅牢性", module: "M02", format: "debug", difficulty: 1,
    question: "AssertionError ではなく ValueError を出したい。正しい書き方は?", code: "assert n > 0",
    answer: "if n <= 0: raise ValueError('neg')", distractors: ["assert ValueError(n > 0)", "raise assert n > 0", "except n > 0"],
    explanation: "条件で明示的に例外型を選ぶなら if で判定して raise する。" },

  { id: "rob-n1-14", category: "プログラム構成・堅牢性", module: "M06", format: "debug", difficulty: 1,
    question: "floor だけを名前で直接使いたい。正しい import は?", code: "___\nprint(floor(3.9))",
    answer: "from math import floor", distractors: ["import math.floor", "from math.floor import", "import floor from math"],
    explanation: "from モジュール import 名前 で個別の関数を直接呼べる。" },

  // ===== d2 (9問) rob-n2-01〜09 =====
  { id: "rob-n2-01", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "try:\n    x = int('5')\nexcept ValueError:\n    print('ve')\nelse:\n    print('else')",
    answer: "else", distractors: ["ve", "5", "エラー"],
    explanation: "try が例外なく成功したので else 節が走り 'else' を出力。" },

  { id: "rob-n2-02", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "出力を順に並べると?", code: "try:\n    raise KeyError('k')\nexcept LookupError:\n    print('lookup')\nfinally:\n    print('fin')",
    answer: "lookup fin", distractors: ["fin lookup", "lookup", "fin"],
    explanation: "KeyError は LookupError の subclass なので捕捉され、その後 finally も実行される。" },

  { id: "rob-n2-03", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "try:\n    try:\n        raise ValueError('inner')\n    except KeyError:\n        print('key')\nexcept ValueError:\n    print('val')",
    answer: "val", distractors: ["key", "inner", "エラー"],
    explanation: "内側は KeyError しか捕まえないので ValueError は外側へ伝播し 'val' を出力。" },

  { id: "rob-n2-04", category: "プログラム構成・堅牢性", module: "M02", format: "fill", difficulty: 2,
    question: "捕まえた例外を再送出して呼び出し元へ伝える、引数なしの文は?", code: "try:\n    risky()\nexcept Exception:\n    log()\n    ___",
    answer: "raise", distractors: ["raise e", "return", "pass"],
    explanation: "引数なしの raise は現在処理中の例外をそのまま再送出する。" },

  { id: "rob-n2-05", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "def f(x: int) -> int:\n    return x\nprint(f('ab') * 2)",
    answer: "abab", distractors: ["エラー", "ab", "4"],
    explanation: "型ヒントは実行時に強制されないので 'ab' がそのまま渡り 'ab'*2 で 'abab'。" },

  { id: "rob-n2-06", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "try:\n    raise IndexError()\nexcept LookupError:\n    print('A')\nexcept IndexError:\n    print('B')",
    answer: "A", distractors: ["B", "A B", "エラー"],
    explanation: "上から順に評価され、先に書いた基底クラス LookupError が IndexError を捕捉する。" },

  { id: "rob-n2-07", category: "プログラム構成・堅牢性", module: "M06", format: "output", difficulty: 2,
    question: "次のコードの出力は?", code: "import math\nprint(math.__name__)",
    answer: "math", distractors: ["__main__", "module", "math.py"],
    explanation: "モジュールオブジェクトの __name__ 属性はそのモジュール名 'math'。" },

  { id: "rob-n2-08", category: "プログラム構成・堅牢性", module: "M02", format: "debug", difficulty: 2,
    question: "具体的な例外を握りつぶさず処理し、想定外は伝播させたい。except 順序として正しいのは?",
    answer: "具体的な FileNotFoundError を先に、一般的な Exception を後に書く",
    distractors: ["一般的な Exception を先に、具体的な型を後に書く", "全て except: だけにまとめる", "順序はどう書いても同じ"],
    explanation: "except は上から評価されるので、具体的な型を先に書かないと一般型に先取りされる。" },

  { id: "rob-n2-09", category: "プログラム構成・堅牢性", module: "M02", format: "debug", difficulty: 2,
    question: "例外オブジェクトをメッセージ付きで使いたい。正しい except 節は?", code: "try:\n    ...\nexcept ValueError ___:\n    print(e)",
    answer: "as e", distractors: ["= e", ", e", "-> e"],
    explanation: "except 型 as 名前 で捕捉した例外を変数に束縛する。" },

  // ===== d3 (9問) rob-n3-01〜09 =====
  { id: "rob-n3-01", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "出力を順に並べると?", code: "def f():\n    try:\n        return 'try'\n    finally:\n        print('fin')\nprint(f())",
    answer: "fin try", distractors: ["try fin", "try", "fin"],
    explanation: "return の値は保留され finally が先に実行されるので 'fin' を出力後に 'try' が返る。" },

  { id: "rob-n3-02", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "出力を順に並べると?", code: "for i in range(3):\n    try:\n        if i == 1:\n            break\n        print(i)\n    finally:\n        print('f', i)",
    answer: "0 f 0 f 1", distractors: ["0 f 0 1 f 1", "0 1 f 0 f 1", "0 f 0"],
    explanation: "break の前にも finally は実行される。i=0 で 0,f 0、i=1 は break 前に f 1。" },

  { id: "rob-n3-03", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "class MyErr(Exception):\n    pass\ntry:\n    try:\n        raise ValueError('v')\n    except ValueError:\n        raise MyErr('m')\nexcept MyErr as e:\n    print(e)",
    answer: "m", distractors: ["v", "MyErr", "エラー"],
    explanation: "except 内で別の例外 MyErr を raise すると外側で捕捉され 'm' を出力。" },

  { id: "rob-n3-04", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "try:\n    try:\n        raise ValueError('v')\n    except ValueError as e:\n        raise RuntimeError('r') from e\nexcept RuntimeError as e:\n    print(e.__cause__)",
    answer: "v", distractors: ["r", "None", "エラー"],
    explanation: "raise ... from e は元例外を __cause__ に保持するため、その文字列表現は 'v'。" },

  { id: "rob-n3-05", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "try:\n    raise ValueError('a')\nexcept Exception:\n    print('general')\nexcept ValueError:\n    print('value')",
    answer: "general", distractors: ["value", "general value", "エラー"],
    explanation: "上から評価されるので先に書いた Exception が捕捉し、後の ValueError は到達しない。" },

  { id: "rob-n3-06", category: "プログラム構成・堅牢性", module: "M02", format: "output", difficulty: 3,
    question: "次のコードの出力は?", code: "def g():\n    try:\n        return 1\n    finally:\n        return 2\nprint(g())",
    answer: "2", distractors: ["1", "1 2", "エラー"],
    explanation: "finally 内の return が try の return を上書きするため 2 が返る。" },

  { id: "rob-n3-07", category: "プログラム構成・堅牢性", module: "M04", format: "output", difficulty: 3,
    question: "出力を順に並べると?", code: "from contextlib import contextmanager\n@contextmanager\ndef cm():\n    print('a')\n    yield\n    print('b')\nwith cm():\n    print('body')",
    answer: "a body b", distractors: ["a b body", "body a b", "a body"],
    explanation: "yield 前が入り口、yield 後が出口なので a -> body -> b の順に出力される。" },

  { id: "rob-n3-08", category: "プログラム構成・堅牢性", module: "M02", format: "fill", difficulty: 3,
    question: "python3 -O などで実行すると無効化され、本番の入力検証に頼ってはいけない文は?",
    answer: "assert", distractors: ["raise", "try", "with"],
    explanation: "assert は最適化フラグ -O で除去されるため、本番の検証には raise を使う。" },

  { id: "rob-n3-09", category: "プログラム構成・堅牢性", module: "M02", format: "fill", difficulty: 3,
    question: "raise ... from e で元の例外が記録される属性名は?", code: "except A as e:\n    raise B() from e\n# 後で e2.______ で元例外を参照",
    answer: "__cause__", distractors: ["__context__", "__traceback__", "__args__"],
    explanation: "明示的な raise ... from e では元例外が __cause__ に設定される。" }
];
